In [53]:
from sklearn.datasets import load_iris
import pandas as pd

# Load Iris dataset
iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add target column
df["target"] = iris.target

# Add target names
df["target_name"] = df["target"].map(
    dict(enumerate(iris.target_names))
)

print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target target_name
0       0      setosa
1       0      setosa
2       0      setosa
3       0      setosa
4       0      setosa

In [54]:
df.rename(columns={"sepal length (cm)" : "sepallengthcm" , "sepal width (cm)" : "sepallengthcm" , "petal length (cm)" : "petallengthcm" , "petal width (cm)" : "petallengthcm"},inplace=True)

In [55]:
df.drop(columns=["target"] , inplace = True)

In [56]:
df.sample(10)

     sepallengthcm  sepallengthcm  petallengthcm  petallengthcm target_name
68             6.2            2.2            4.5            1.5  versicolor
133            6.3            2.8            5.1            1.5   virginica
11             4.8            3.4            1.6            0.2      setosa
55             5.7            2.8            4.5            1.3  versicolor
102            7.1            3.0            5.9            2.1   virginica
83             6.0            2.7            5.1            1.6  versicolor
99             5.7            2.8            4.1            1.3  versicolor
26             5.0            3.4            1.6            0.4      setosa
81             5.5            2.4            3.7            1.0  versicolor
140            6.7            3.1            5.6            2.4   virginica

In [57]:
# Label encode Species
from sklearn.preprocessing import LabelEncoder

In [58]:
encoder = LabelEncoder()

In [59]:
df['target_name'] = encoder.fit_transform(df['target_name'])

In [60]:
df.sample(10)

     sepallengthcm  sepallengthcm  petallengthcm  petallengthcm  target_name
56             6.3            3.3            4.7            1.6            1
68             6.2            2.2            4.5            1.5            1
81             5.5            2.4            3.7            1.0            1
24             4.8            3.4            1.9            0.2            0
116            6.5            3.0            5.5            1.8            2
44             5.1            3.8            1.9            0.4            0
16             5.4            3.9            1.3            0.4            0
33             5.5            4.2            1.4            0.2            0
133            6.3            2.8            5.1            1.5            2
146            6.3            2.5            5.0            1.9            2

In [86]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [87]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [88]:
clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = KNeighborsClassifier()

In [89]:
estimators = [('lr',clf1),('rf',clf2),('knn',clf3)]

In [90]:
import numpy as np
for estimator in estimators:
    x = cross_val_score(estimator[1],X,y,cv=10,scoring='accuracy')
    print(estimator[0],np.round(np.mean(x),2))

lr 0.81
rf 0.71
knn 0.76

In [91]:
from sklearn.ensemble import VotingClassifier

## Hard Voting

In [92]:
vc = VotingClassifier(estimators=estimators,voting='hard')
x = cross_val_score(vc,X,y,cv=10,scoring='accuracy')
print(np.round(np.mean(x),2))

0.77

## Soft Voting

In [93]:
vc1 = VotingClassifier(estimators=estimators,voting='soft')
x = cross_val_score(vc1,X,y,cv=10,scoring='accuracy')
print(np.round(np.mean(x),2))

0.77

## Weighted Voting

In [95]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vc = VotingClassifier(estimators=estimators,voting='soft',weights=[i,j,k])
            x = cross_val_score(vc,X,y,cv=10,scoring='accuracy')
            print("for i={},j={},k={}".format(i,j,k),np.round(np.mean(x),2))

for i=1,j=1,k=1 0.77
for i=1,j=1,k=2 0.77
for i=1,j=1,k=3 0.77
for i=1,j=2,k=1 0.75
for i=1,j=2,k=2 0.75
for i=1,j=2,k=3 0.75
for i=1,j=3,k=1 0.73
for i=1,j=3,k=2 0.74
for i=1,j=3,k=3 0.75
for i=2,j=1,k=1 0.77
for i=2,j=1,k=2 0.77
for i=2,j=1,k=3 0.77
for i=2,j=2,k=1 0.77
for i=2,j=2,k=2 0.77
for i=2,j=2,k=3 0.77
for i=2,j=3,k=1 0.75
for i=2,j=3,k=2 0.77
for i=2,j=3,k=3 0.75
for i=3,j=1,k=1 0.8
for i=3,j=1,k=2 0.79
for i=3,j=1,k=3 0.78
for i=3,j=2,k=1 0.78
for i=3,j=2,k=2 0.77
for i=3,j=2,k=3 0.77
for i=3,j=3,k=1 0.76
for i=3,j=3,k=2 0.76
for i=3,j=3,k=3 0.75

## Classifiers of Same Algo

In [96]:
from sklearn.svm import SVC

In [97]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=2)

svm1 = SVC(probability=True, kernel='poly', degree=1)
svm2 = SVC(probability=True, kernel='poly', degree=2)
svm3 = SVC(probability=True, kernel='poly', degree=3)
svm4 = SVC(probability=True, kernel='poly', degree=4)
svm5 = SVC(probability=True, kernel='poly', degree=5)

estimators = [('svm1',svm1),('svm2',svm2),('svm3',svm3),('svm4',svm4),('svm5',svm5)]

for estimator in estimators:
    x = cross_val_score(estimator[1],X,y,cv=10,scoring='accuracy')
    print(estimator[0],np.round(np.mean(x),2))

svm1 0.85
svm2 0.85
svm3 0.89
svm4 0.81
svm5 0.86

In [98]:
vc1 = VotingClassifier(estimators=estimators,voting='soft')
x = cross_val_score(vc1,X,y,cv=10,scoring='accuracy')
print(np.round(np.mean(x),2))

0.93