In [44]:
import pandas as pd
import requests

In [45]:
url = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"

symbols = pd.read_csv(url)

symbols[symbols["SYMBOL"] == "SAMMAANCAP"]

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE
1809,SAMMAANCAP,Sammaan Capital Limited,EQ,23-JUL-2013,2,1,INE148I01020,2

In [46]:
nseCodes = symbols["SYMBOL"]
nseCodes

0        20MICRONS
1       21STCENMGM
2           360ONE
3       3BBLACKBIO
4        3IINFOLTD
           ...
2367      ZSARACOM
2368         ZUARI
2369      ZUARIIND
2370     ZYDUSLIFE
2371     ZYDUSWELL
Name: SYMBOL, Length: 2372, dtype: object

In [47]:
    url = "https://api.twelvedata.com/quote?symbol=INFY&exchange=NSE&apikey=42a6157ef30c4ad9a180f7243dd734f7"

In [48]:
response = requests.get(url)
temp_df = pd.json_normalize(response.json())

In [49]:
temp_df

   code                                            message status
0   429  You have run out of API credits for the day. 1...  error

In [50]:
df = pd.DataFrame()

In [51]:
for i in range(10):
    response = requests.get(f"https://api.twelvedata.com/quote?symbol={nseCodes[i]}&exchange=NSE&apikey=42a6157ef30c4ad9a180f7243dd734f7")
    temp_df = pd.json_normalize(response.json())
    df = pd.concat([df, temp_df], ignore_index=True)

In [52]:
df

   code                                            message status
0   429  You have run out of API credits for the day. 1...  error
1   429  You have run out of API credits for the day. 1...  error
2   429  You have run out of API credits for the day. 1...  error
3   429  You have run out of API credits for the day. 1...  error
4   429  You have run out of API credits for the day. 1...  error
5   429  You have run out of API credits for the day. 1...  error
6   429  You have run out of API credits for the day. 1...  error
7   429  You have run out of API credits for the day. 1...  error
8   429  You have run out of API credits for the day. 1...  error
9   429  You have run out of API credits for the day. 1...  error