In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame({"Name": ["Het", "Raj", "Jay"],"Age": [21, np.nan, 22],"Salary": [50000, 45000, np.nan]})

print(df)

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj   NaN  45000.0
2  Jay  22.0      NaN

In [8]:
# PART 2 — isna()
df.isna() # True = Missing value found.

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [9]:
# PART 3 — Count Missing Values
df.isna().sum() # Missing values per column

# Why does this work?
# Because:
# True = 1
# False = 0
# So .sum() counts missing values.

Name      0
Age       1
Salary    1
dtype: int64

In [10]:
# PART 4 — Missing Values Percentage
(df.isna().sum() / len(df)) * 100

Name       0.000000
Age       33.333333
Salary    33.333333
dtype: float64

In [11]:
# PART 5 — notna()
# Opposite of isna().
df.notna()

# True = valid value
# False = missing value

   Name    Age  Salary
0  True   True    True
1  True  False    True
2  True   True   False

In [12]:
# PART 6 — Dropping Missing Values (dropna()) 
# Removes rows or columns containing missing values.

# Axis	   Meaning
# axis=0	Rows
# axis=1	Columns

In [13]:
# 1. Remove Rows with Missing Values
df.dropna()

  Name   Age   Salary
0  Het  21.0  50000.0

In [14]:
# 2. Remove Columns with Missing Values
df.dropna(axis=1)

  Name
0  Het
1  Raj
2  Jay

In [15]:
# 3. Remove Only if ALL Values Missing
df.dropna(how="all")

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj   NaN  45000.0
2  Jay  22.0      NaN

In [16]:
# 4. Remove Only if ANY Value Missing
df.dropna(how="any")

  Name   Age   Salary
0  Het  21.0  50000.0

In [17]:
# 5. Threshold (thresh) 
# Keep rows having minimum non-null values.
df.dropna(thresh=2) # Keep rows with at least 2 non-missing values.

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj   NaN  45000.0
2  Jay  22.0      NaN

In [18]:
# PART 7 — Filling Missing Values (fillna()) 
# Instead of deleting data, we fill missing values.
# This is MOST COMMON in Machine Learning.

In [19]:
# 1. Fill with Constant Value
df.fillna(0)

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj   0.0  45000.0
2  Jay  22.0      0.0

In [20]:
df.fillna("Unknown")

  Name      Age   Salary
0  Het     21.0  50000.0
1  Raj  Unknown  45000.0
2  Jay     22.0  Unknown

In [21]:
# 2. Fill Specific Column
df["Age"].fillna(0)

0    21.0
1     0.0
2    22.0
Name: Age, dtype: float64

In [22]:
# 3. Fill Using Mean 
df["Age"].fillna(df["Age"].mean())

0    21.0
1    21.5
2    22.0
Name: Age, dtype: float64

In [23]:
# 4. Fill Using Median
# Better when outliers exist.
df["Salary"].fillna(df["Salary"].median())

0    50000.0
1    45000.0
2    47500.0
Name: Salary, dtype: float64

In [24]:
# 5. Fill Using Mode
df["Salary"].fillna(df["Salary"].mode()[0])

0    50000.0
1    45000.0
2    45000.0
Name: Salary, dtype: float64

In [27]:
# PART 8 — Forward Fill (ffill)
# Uses previous value.
df.fillna(method="ffill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_20696\1368427454.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj  21.0  45000.0
2  Jay  22.0  45000.0

In [28]:
# PART 9 — Backward Fill (bfill)
# Uses next value.
df.fillna(method="bfill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_20696\4104612588.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj  22.0  45000.0
2  Jay  22.0      NaN

In [29]:
# PART 10 — Interpolation
# Fills mathematically.
df.interpolate()

C:\Users\Admin\AppData\Local\Temp\ipykernel_20696\1910001781.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj  21.5  45000.0
2  Jay  22.0  45000.0

In [31]:
# PART 11 — Replace Missing Values
# Replace None with NaN
# df.replace(None, np.nan)

In [32]:
# PART 12 — Check Rows with Missing Values

# Rows containing NaN
df[df.isna().any(axis=1)]

  Name   Age   Salary
1  Raj   NaN  45000.0
2  Jay  22.0      NaN

In [33]:
# Rows with NO NaN
df[df.notna().all(axis=1)]

  Name   Age   Salary
0  Het  21.0  50000.0

In [36]:
# PART 13 — Sorting Missing Values

In [37]:
# Put NaN first
df.sort_values(by="Age", na_position="first")

  Name   Age   Salary
1  Raj   NaN  45000.0
0  Het  21.0  50000.0
2  Jay  22.0      NaN

In [38]:
# Put NaN last
df.sort_values(by="Age", na_position="last")

  Name   Age   Salary
0  Het  21.0  50000.0
2  Jay  22.0      NaN
1  Raj   NaN  45000.0

In [41]:
# PART 14 — Missing Values in GroupBy
print(df)
df.groupby("Age").mean(numeric_only=True)

  Name   Age   Salary
0  Het  21.0  50000.0
1  Raj   NaN  45000.0
2  Jay  22.0      NaN

       Salary
Age
21.0  50000.0
22.0      NaN