In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("employees_missing_data.csv")
print(df)

    EmployeeID   Name Department   Age    Salary  Experience       City  \
0          101    Het         IT  22.0   45000.0         1.0     Rajkot
1          102    Raj         HR   NaN   40000.0         2.0  Ahmedabad
2          103    Jay         IT  25.0       NaN         3.0      Surat
3          104   Amit    Finance  29.0  850000.0         5.0     Rajkot
4          105   Neha         HR  24.0   42000.0         NaN  Ahmedabad
5          106  Priya         IT   NaN   47000.0         2.0        NaN
6          107  Karan    Finance  31.0       NaN         6.0      Surat
7          108   Riya  Marketing  26.0   39000.0         3.0     Rajkot
8          109    Dev  Marketing  27.0   41000.0         NaN  Ahmedabad
9          110  Krish         IT  23.0   46000.0         2.0      Surat
10         111   Anya    Finance   NaN  950000.0         7.0     Rajkot
11         112  Parth         HR  28.0   43000.0         4.0        NaN

    PerformanceScore
0                8.0
1                7.0
2                9.0
3                6.0
4                NaN
5                8.0
6                7.0
7                NaN
8                6.0
9                9.0
10               8.0
11               7.0

In [3]:
# 1. Check Missing Values
df.isna().sum()

EmployeeID          0
Name                0
Department          0
Age                 3
Salary              2
Experience          2
City                2
PerformanceScore    2
dtype: int64

In [4]:
# 2. Drop Rows if Very Few Missing
df.dropna()

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,101,Het,IT,22.0,45000.0,1.0,Rajkot,8.0
3,104,Amit,Finance,29.0,850000.0,5.0,Rajkot,6.0
9,110,Krish,IT,23.0,46000.0,2.0,Surat,9.0

In [7]:
# 3. Fill Numerical Data with Median
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
print(df)

    EmployeeID   Name Department   Age    Salary  Experience       City  \
0          101    Het         IT  22.0   45000.0         1.0     Rajkot
1          102    Raj         HR   NaN   40000.0         2.0  Ahmedabad
2          103    Jay         IT  25.0   44000.0         3.0      Surat
3          104   Amit    Finance  29.0  850000.0         5.0     Rajkot
4          105   Neha         HR  24.0   42000.0         NaN  Ahmedabad
5          106  Priya         IT   NaN   47000.0         2.0        NaN
6          107  Karan    Finance  31.0   44000.0         6.0      Surat
7          108   Riya  Marketing  26.0   39000.0         3.0     Rajkot
8          109    Dev  Marketing  27.0   41000.0         NaN  Ahmedabad
9          110  Krish         IT  23.0   46000.0         2.0      Surat
10         111   Anya    Finance   NaN  950000.0         7.0     Rajkot
11         112  Parth         HR  28.0   43000.0         4.0        NaN

    PerformanceScore
0                8.0
1                7.0
2                9.0
3                6.0
4                NaN
5                8.0
6                7.0
7                NaN
8                6.0
9                9.0
10               8.0
11               7.0

In [10]:
# 4. Fill Categorical Data with Mode
df["City"] = df["City"].fillna(df["City"].mode()[0])
print(df)

    EmployeeID   Name Department   Age    Salary  Experience       City  \
0          101    Het         IT  22.0   45000.0         1.0     Rajkot
1          102    Raj         HR   NaN   40000.0         2.0  Ahmedabad
2          103    Jay         IT  25.0   44000.0         3.0      Surat
3          104   Amit    Finance  29.0  850000.0         5.0     Rajkot
4          105   Neha         HR  24.0   42000.0         NaN  Ahmedabad
5          106  Priya         IT   NaN   47000.0         2.0     Rajkot
6          107  Karan    Finance  31.0   44000.0         6.0      Surat
7          108   Riya  Marketing  26.0   39000.0         3.0     Rajkot
8          109    Dev  Marketing  27.0   41000.0         NaN  Ahmedabad
9          110  Krish         IT  23.0   46000.0         2.0      Surat
10         111   Anya    Finance   NaN  950000.0         7.0     Rajkot
11         112  Parth         HR  28.0   43000.0         4.0     Rajkot

    PerformanceScore
0                8.0
1                7.0
2                9.0
3                6.0
4                NaN
5                8.0
6                7.0
7                NaN
8                6.0
9                9.0
10               8.0
11               7.0

In [11]:
# 5. Fill Age with Mean
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

    EmployeeID   Name Department        Age    Salary  Experience       City  \
0          101    Het         IT  22.000000   45000.0         1.0     Rajkot
1          102    Raj         HR  26.111111   40000.0         2.0  Ahmedabad
2          103    Jay         IT  25.000000   44000.0         3.0      Surat
3          104   Amit    Finance  29.000000  850000.0         5.0     Rajkot
4          105   Neha         HR  24.000000   42000.0         NaN  Ahmedabad
5          106  Priya         IT  26.111111   47000.0         2.0     Rajkot
6          107  Karan    Finance  31.000000   44000.0         6.0      Surat
7          108   Riya  Marketing  26.000000   39000.0         3.0     Rajkot
8          109    Dev  Marketing  27.000000   41000.0         NaN  Ahmedabad
9          110  Krish         IT  23.000000   46000.0         2.0      Surat
10         111   Anya    Finance  26.111111  950000.0         7.0     Rajkot
11         112  Parth         HR  28.000000   43000.0         4.0     Rajkot

    PerformanceScore
0                8.0
1                7.0
2                9.0
3                6.0
4                NaN
5                8.0
6                7.0
7                NaN
8                6.0
9                9.0
10               8.0
11               7.0

In [12]:
# 6. Group-Based Filling
# Fill salary based on department average.
df["Salary"] = (df.groupby("Department")["Salary"].transform(lambda x : x.fillna(x.mean())))
print(df)

    EmployeeID   Name Department        Age    Salary  Experience       City  \
0          101    Het         IT  22.000000   45000.0         1.0     Rajkot
1          102    Raj         HR  26.111111   40000.0         2.0  Ahmedabad
2          103    Jay         IT  25.000000   44000.0         3.0      Surat
3          104   Amit    Finance  29.000000  850000.0         5.0     Rajkot
4          105   Neha         HR  24.000000   42000.0         NaN  Ahmedabad
5          106  Priya         IT  26.111111   47000.0         2.0     Rajkot
6          107  Karan    Finance  31.000000   44000.0         6.0      Surat
7          108   Riya  Marketing  26.000000   39000.0         3.0     Rajkot
8          109    Dev  Marketing  27.000000   41000.0         NaN  Ahmedabad
9          110  Krish         IT  23.000000   46000.0         2.0      Surat
10         111   Anya    Finance  26.111111  950000.0         7.0     Rajkot
11         112  Parth         HR  28.000000   43000.0         4.0     Rajkot

    PerformanceScore
0                8.0
1                7.0
2                9.0
3                6.0
4                NaN
5                8.0
6                7.0
7                NaN
8                6.0
9                9.0
10               8.0
11               7.0

In [13]:
# 7. Forward Fill
df.fillna(method="ffill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_16932\1807377827.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,101,Het,IT,22.000000,45000.0,1.0,Rajkot,8.0
1,102,Raj,HR,26.111111,40000.0,2.0,Ahmedabad,7.0
2,103,Jay,IT,25.000000,44000.0,3.0,Surat,9.0
3,104,Amit,Finance,29.000000,850000.0,5.0,Rajkot,6.0
4,105,Neha,HR,24.000000,42000.0,5.0,Ahmedabad,6.0
5,106,Priya,IT,26.111111,47000.0,2.0,Rajkot,8.0
6,107,Karan,Finance,31.000000,44000.0,6.0,Surat,7.0
7,108,Riya,Marketing,26.000000,39000.0,3.0,Rajkot,7.0
8,109,Dev,Marketing,27.000000,41000.0,3.0,Ahmedabad,6.0
9,110,Krish,IT,23.000000,46000.0,2.0,Surat,9.0
10,111,Anya,Finance,26.111111,950000.0,7.0,Rajkot,8.0
11,112,Parth,HR,28.000000,43000.0,4.0,Rajkot,7.0

In [14]:
# 8. Backward Fill
df.fillna(method="bfill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_16932\309673949.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,101,Het,IT,22.000000,45000.0,1.0,Rajkot,8.0
1,102,Raj,HR,26.111111,40000.0,2.0,Ahmedabad,7.0
2,103,Jay,IT,25.000000,44000.0,3.0,Surat,9.0
3,104,Amit,Finance,29.000000,850000.0,5.0,Rajkot,6.0
4,105,Neha,HR,24.000000,42000.0,2.0,Ahmedabad,8.0
5,106,Priya,IT,26.111111,47000.0,2.0,Rajkot,8.0
6,107,Karan,Finance,31.000000,44000.0,6.0,Surat,7.0
7,108,Riya,Marketing,26.000000,39000.0,3.0,Rajkot,6.0
8,109,Dev,Marketing,27.000000,41000.0,2.0,Ahmedabad,6.0
9,110,Krish,IT,23.000000,46000.0,2.0,Surat,9.0
10,111,Anya,Finance,26.111111,950000.0,7.0,Rajkot,8.0
11,112,Parth,HR,28.000000,43000.0,4.0,Rajkot,7.0

In [15]:
# 9. Remove Mostly Empty Columns
(df.isna().sum() / len(df)) * 100

EmployeeID           0.000000
Name                 0.000000
Department           0.000000
Age                  0.000000
Salary               0.000000
Experience          16.666667
City                 0.000000
PerformanceScore    16.666667
dtype: float64