In [48]:
import pandas as pd

In [49]:
df = pd.read_csv("pokemon_150.csv")

In [50]:
# sort_values() — Sort by Column Values
# Sort Ascending (Default)
print(df.sort_values(by = "Weight"))

      No        Name     Type1     Type2  Height  Weight  Legendary
38    39  Jigglypuff    Poison     Water     0.6     2.0          0
92    93     Haunter    Flying  Electric     3.7     2.2          0
43    44       Gloom      Fire    Flying     3.7     2.3          0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0
..   ...         ...       ...       ...     ...     ...        ...
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0
25    26      Raichu   Psychic    Poison     3.3    98.6          0
132  133       Eevee     Grass    Flying     2.2    98.9          0

[150 rows x 7 columns]

In [51]:
# Sort Descending
print(df.sort_values(by = "Weight" , ascending=False))

      No        Name     Type1     Type2  Height  Weight  Legendary
132  133       Eevee     Grass    Flying     2.2    98.9          0
25    26      Raichu   Psychic    Poison     3.3    98.6          0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0
..   ...         ...       ...       ...     ...     ...        ...
4      5  Charmeleon    Normal    Poison     2.4     3.1          0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0
43    44       Gloom      Fire    Flying     3.7     2.3          0
92    93     Haunter    Flying  Electric     3.7     2.2          0
38    39  Jigglypuff    Poison     Water     0.6     2.0          0

[150 rows x 7 columns]

In [52]:
# Sort by Multiple Columns
print(df.sort_values(by = ["Weight" , "Height"])) # First sort by Weight , If Weight are same → sorts by Height.

      No        Name     Type1     Type2  Height  Weight  Legendary
38    39  Jigglypuff    Poison     Water     0.6     2.0          0
92    93     Haunter    Flying  Electric     3.7     2.2          0
43    44       Gloom      Fire    Flying     3.7     2.3          0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0
..   ...         ...       ...       ...     ...     ...        ...
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0
25    26      Raichu   Psychic    Poison     3.3    98.6          0
132  133       Eevee     Grass    Flying     2.2    98.9          0

[150 rows x 7 columns]

In [53]:
# Different order for different columns
print(df.sort_values(by = ["Weight" , "Height"] , ascending = [True , False]))

      No        Name     Type1     Type2  Height  Weight  Legendary
38    39  Jigglypuff    Poison     Water     0.6     2.0          0
92    93     Haunter    Flying  Electric     3.7     2.2          0
43    44       Gloom      Fire    Flying     3.7     2.3          0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0
..   ...         ...       ...       ...     ...     ...        ...
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0
25    26      Raichu   Psychic    Poison     3.3    98.6          0
132  133       Eevee     Grass    Flying     2.2    98.9          0

[150 rows x 7 columns]

In [54]:
# Permanent Sorting (inplace=True)
# Normally sorting creates new dataframe.
df.sort_values(by = "Weight" , inplace = True)

In [55]:
print(df)
# Original dataframe changes permanently.

      No        Name     Type1     Type2  Height  Weight  Legendary
38    39  Jigglypuff    Poison     Water     0.6     2.0          0
92    93     Haunter    Flying  Electric     3.7     2.2          0
43    44       Gloom      Fire    Flying     3.7     2.3          0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0
..   ...         ...       ...       ...     ...     ...        ...
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0
25    26      Raichu   Psychic    Poison     3.3    98.6          0
132  133       Eevee     Grass    Flying     2.2    98.9          0

[150 rows x 7 columns]

In [56]:
# Reset Index After Sorting
# After sorting index becomes messy.
df.sort_values(by = "Weight").reset_index(drop=True)

      No        Name     Type1     Type2  Height  Weight  Legendary
0     39  Jigglypuff    Poison     Water     0.6     2.0          0
1     93     Haunter    Flying  Electric     3.7     2.2          0
2     44       Gloom      Fire    Flying     3.7     2.3          0
3    138     Omanyte  Electric   Psychic     0.9     2.7          0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0
..   ...         ...       ...       ...     ...     ...        ...
145   32    NidoranM   Psychic    Dragon     2.5    96.5          0
146   31   Nidoqueen    Flying       NaN     3.3    97.2          0
147   51     Dugtrio  Electric      Rock     0.7    98.2          0
148   26      Raichu   Psychic    Poison     3.3    98.6          0
149  133       Eevee     Grass    Flying     2.2    98.9          0

[150 rows x 7 columns]

In [57]:
# Sort by Index — sort_index()
# Sorts using row labels/index.
df.sort_index()

      No        Name   Type1    Type2  Height  Weight  Legendary
0      1   Bulbasaur    Fire     Fire     2.1    91.1          0
1      2     Ivysaur   Water     Fire     1.2     6.6          0
2      3    Venusaur    Fire    Grass     1.4    17.6          0
3      4  Charmander  Flying   Dragon     1.4    29.0          0
4      5  Charmeleon  Normal   Poison     2.4     3.1          0
..   ...         ...     ...      ...     ...     ...        ...
145  146     Moltres  Dragon   Flying     3.3    54.6          1
146  147     Dratini    Rock   Flying     3.5    49.2          0
147  148   Dragonair  Poison    Grass     1.8    70.5          0
148  149   Dragonite  Flying  Psychic     1.3    40.1          0
149  150      Mewtwo   Water      NaN     2.9    70.6          1

[150 rows x 7 columns]

In [58]:
# Sorting Strings
# Sorts alphabetically.
df.sort_values(by="Name")

      No        Name     Type1   Type2  Height  Weight  Legendary
62    63        Abra      Fire    Rock     0.5    28.5          0
141  142  Aerodactyl    Poison  Poison     1.0    36.7          0
64    65    Alakazam    Flying  Normal     0.8    11.5          0
23    24       Arbok   Psychic    Fire     0.5    83.9          0
58    59    Arcanine    Flying  Normal     0.9    92.8          0
..   ...         ...       ...     ...     ...     ...        ...
69    70  Weepinbell  Electric  Poison     1.4    10.2          0
109  110     Weezing      Rock    Fire     3.6    34.9          0
39    40  Wigglytuff     Grass    Fire     3.5     6.3          0
144  145      Zapdos  Electric   Grass     2.7    36.7          1
40    41       Zubat    Poison    Fire     1.4    78.5          0

[150 rows x 7 columns]

In [59]:
# Sorting Missing Values (NaN)
# Should missing values appear at the top?
# Or at the bottom?
df.sort_values(by = "Type2" , na_position="first")

      No        Name   Type1  Type2  Height  Weight  Legendary
53    54     Psyduck   Grass    NaN     2.6     9.1          0
12    13      Weedle  Dragon    NaN     2.1    10.6          0
11    12  Butterfree    Fire    NaN     2.3    14.8          0
99   100     Voltorb   Grass    NaN     2.2    27.1          0
55    56      Mankey    Rock    NaN     0.3    29.0          0
..   ...         ...     ...    ...     ...     ...        ...
65    66      Machop  Dragon  Water     3.0    56.1          0
57    58   Growlithe  Normal  Water     3.8    49.3          0
101  102   Exeggcute   Water  Water     0.5    47.1          0
95    96     Drowzee    Rock  Water     2.7    89.5          0
38    39  Jigglypuff  Poison  Water     0.6     2.0          0

[150 rows x 7 columns]

In [60]:
df.sort_values(by = "Type2" , na_position="last")

      No       Name     Type1   Type2  Height  Weight  Legendary
32    33   Nidorino   Psychic  Dragon     0.6    19.7          0
31    32   NidoranM   Psychic  Dragon     2.5    96.5          0
59    60    Poliwag     Water  Dragon     1.8    39.7          0
117  118    Goldeen     Grass  Dragon     1.9    17.5          0
116  117     Seadra      Rock  Dragon     1.1    44.4          0
..   ...        ...       ...     ...     ...     ...        ...
37    38  Ninetales  Electric     NaN     1.0    45.4          0
17    18    Pidgeot     Grass     NaN     2.9    50.5          0
94    95       Onix   Psychic     NaN     3.0    59.6          0
149  150     Mewtwo     Water     NaN     2.9    70.6          1
30    31  Nidoqueen    Flying     NaN     3.3    97.2          0

[150 rows x 7 columns]

In [61]:
# Largest & Smallest Values
df.nlargest(3, "Height")

      No        Name    Type1   Type2  Height  Weight  Legendary
143  144    Articuno     Rock    Fire     3.9    25.2          1
87    88      Grimer  Psychic    Rock     3.9    25.8          0
72    73  Tentacruel     Fire  Poison     3.9    53.6          0

In [62]:
df.nsmallest(3, "Height")

      No     Name   Type1   Type2  Height  Weight  Legendary
55    56   Mankey    Rock     NaN     0.3    29.0          0
108  109  Koffing  Flying  Poison     0.4    34.9          0
120  121  Starmie   Water   Water     0.4    47.9          0

In [63]:
# Ranking

In [64]:
# rank() Function
df["Weight"].rank()

38       1.0
92       2.0
43       3.0
137      4.0
4        5.0
       ...
31     146.0
30     147.0
50     148.0
25     149.0
132    150.0
Name: Weight, Length: 150, dtype: float64

In [65]:
df["Rank"] = df["Weight"].rank()

In [66]:
print(df)

      No        Name     Type1     Type2  Height  Weight  Legendary   Rank
38    39  Jigglypuff    Poison     Water     0.6     2.0          0    1.0
92    93     Haunter    Flying  Electric     3.7     2.2          0    2.0
43    44       Gloom      Fire    Flying     3.7     2.3          0    3.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0    4.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0    5.0
..   ...         ...       ...       ...     ...     ...        ...    ...
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0  146.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0  147.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  148.0
25    26      Raichu   Psychic    Poison     3.3    98.6          0  149.0
132  133       Eevee     Grass    Flying     2.2    98.9          0  150.0

[150 rows x 8 columns]

In [67]:
# Highest Rank First
df2 = pd.read_csv("pokemon_150.csv")
df2["Weight"].rank(ascending=False)

0       15.0
1      142.0
2      124.0
3      108.5
4      146.0
       ...
145     65.0
146     76.0
147     42.0
148     92.0
149     40.5
Name: Weight, Length: 150, dtype: float64

In [68]:
# Ranking Methods
# When duplicate values exist:

In [69]:
# Method 1 — average (Default)
df2["Rank"] = df2["Height"].rank(method="average" , ascending = False)
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary   Rank
0      1   Bulbasaur      Fire      Fire     2.1    91.1          0   76.0
1      2     Ivysaur     Water      Fire     1.2     6.6          0  111.5
2      3    Venusaur      Fire     Grass     1.4    17.6          0  102.0
3      4  Charmander    Flying    Dragon     1.4    29.0          0  102.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0   59.0
5      6   Charizard    Flying       NaN     2.7    33.9          0   44.0
6      7    Squirtle    Dragon      Rock     2.3    41.1          0   65.5
7      8   Wartortle      Fire   Psychic     2.7    38.5          0   44.0
8      9   Blastoise    Flying  Electric     1.1    49.3          0  116.0
9     10    Caterpie     Water  Electric     1.2    16.0          0  111.5
10    11     Metapod      Fire   Psychic     0.4    67.7          0  147.5
11    12  Butterfree      Fire       NaN     2.3    14.8          0   65.5
12    13      Weedle    Dragon       NaN     2.1    10.6          0   76.0
13    14      Kakuna    Flying      Rock     3.1    14.0          0   30.5
14    15    Beedrill  Electric    Poison     1.9    75.7          0   83.5
15    16      Pidgey    Dragon      Rock     1.4    94.8          0  102.0
16    17   Pidgeotto    Flying    Normal     1.7    33.4          0   90.0
17    18     Pidgeot     Grass       NaN     2.9    50.5          0   37.5
18    19     Rattata      Fire  Electric     2.0    88.7          0   80.0
19    20    Raticate    Dragon     Grass     0.8    31.4          0  130.0
20    21     Spearow      Rock    Normal     3.6    63.3          0   16.0
21    22      Fearow    Poison    Poison     2.1    92.3          0   76.0
22    23       Ekans      Rock    Poison     3.0    55.4          0   34.0
23    24       Arbok   Psychic      Fire     0.5    83.9          0  143.0
24    25     Pikachu    Poison    Poison     2.3    13.2          0   65.5
25    26      Raichu   Psychic    Poison     3.3    98.6          0   25.5
26    27   Sandshrew  Electric   Psychic     2.8    46.8          0   39.5
27    28   Sandslash    Dragon    Poison     3.3    67.0          0   25.5
28    29    NidoranF   Psychic      Rock     3.5    89.4          0   21.0
29    30    Nidorina   Psychic      Fire     0.5    93.5          0  143.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0   25.5
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0   54.5
32    33    Nidorino   Psychic    Dragon     0.6    19.7          0  138.0
33    34    Nidoking     Water     Water     0.6    68.3          0  138.0
34    35    Clefairy    Normal    Flying     0.5    48.1          0  143.0
35    36    Clefable     Water     Grass     2.6    51.0          0   50.5
36    37      Vulpix      Rock     Grass     0.9    68.0          0  125.0
37    38   Ninetales  Electric       NaN     1.0    45.4          0  120.5
38    39  Jigglypuff    Poison     Water     0.6     2.0          0  138.0
39    40  Wigglytuff     Grass      Fire     3.5     6.3          0   21.0
40    41       Zubat    Poison      Fire     1.4    78.5          0  102.0
41    42      Golbat   Psychic    Poison     2.3    19.4          0   65.5
42    43      Oddish     Water      Rock     3.7    13.4          0   10.5
43    44       Gloom      Fire    Flying     3.7     2.3          0   10.5
44    45   Vileplume    Flying    Normal     1.5    43.1          0   97.0
45    46       Paras    Normal      Rock     1.9    70.6          0   83.5
46    47    Parasect    Flying      Rock     1.3    90.0          0  107.0
47    48     Venonat  Electric  Electric     2.0    81.7          0   80.0
48    49    Venomoth    Normal    Normal     2.8    78.6          0   39.5
49    50     Diglett    Normal     Water     2.4     4.5          0   59.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  134.5
51    52      Meowth   Psychic     Grass     3.7    41.4          0   10.5
52    53     Persian      Fire  Electric     0.6    49.5          0  138.0
53    54     Psyduck     Grass       NaN     2.6     9.1          0   50.5
54    55     Golduck    Dragon  Electric     1.0    14.8          0  120.5
55    56      Mankey      Rock       NaN     0.3    29.0          0  150.0
56    57    Primeape   Psychic    Poison     1.9     3.5          0   83.5
57    58   Growlithe    Normal     Water     3.8    49.3          0    6.0
58    59    Arcanine    Flying    Normal     0.9    92.8          0  125.0
59    60     Poliwag     Water    Dragon     1.8    39.7          0   87.5
60    61   Poliwhirl    Normal      Rock     1.5    43.2          0   97.0
61    62   Poliwrath    Poison      Fire     2.4    69.2          0   59.0
62    63        Abra      Fire      Rock     0.5    28.5          0  143.0
63    64     Kadabra    Dragon    Flying     3.2    69.3          0   28.5
64    65    Alakazam    Flying    Normal     0.8    11.5          0  130.0
65    66      Machop    Dragon     Water     3.0    56.1          0   34.0
66    67     Machoke    Poison      Rock     3.9    55.7          0    2.5
67    68     Machamp    Flying    Poison     0.8    66.8          0  130.0
68    69  Bellsprout   Psychic  Electric     1.6    16.3          0   93.0
69    70  Weepinbell  Electric    Poison     1.4    10.2          0  102.0
70    71  Victreebel    Poison       NaN     2.6    37.0          0   50.5
71    72   Tentacool     Grass   Psychic     0.8     8.0          0  130.0
72    73  Tentacruel      Fire    Poison     3.9    53.6          0    2.5
73    74     Geodude    Dragon    Flying     0.6    84.2          0  138.0
74    75    Graveler    Normal    Dragon     1.4    17.3          0  102.0
75    76       Golem    Flying     Grass     3.1    68.2          0   30.5
76    77      Ponyta    Dragon   Psychic     1.4    74.6          0  102.0
77    78    Rapidash     Water   Psychic     2.6    69.5          0   50.5
78    79    Slowpoke    Normal      Fire     3.0    41.9          0   34.0
79    80     Slowbro     Water   Psychic     2.2    55.3          0   71.0
80    81   Magnemite     Grass    Flying     1.2    53.1          0  111.5
81    82    Magneton     Grass  Electric     2.7    58.9          0   44.0
82    83   Farfetchd     Water     Water     1.0    86.6          0  120.5
83    84       Doduo     Water    Normal     2.1    33.7          0   76.0
84    85      Dodrio     Water    Normal     3.7    21.2          0   10.5
85    86        Seel    Flying      Fire     2.7    77.4          0   44.0
86    87     Dewgong  Electric     Grass     2.4    67.0          0   59.0
87    88      Grimer   Psychic      Rock     3.9    25.8          0    2.5
88    89         Muk  Electric       NaN     0.8    33.1          0  130.0
89    90    Shellder      Rock  Electric     1.2    84.9          0  111.5
90    91    Cloyster    Dragon  Electric     1.2    80.6          0  111.5
91    92      Gastly    Normal  Electric     2.7    93.2          0   44.0
92    93     Haunter    Flying  Electric     3.7     2.2          0   10.5
93    94      Gengar      Fire    Normal     1.6    76.2          0   93.0
94    95        Onix   Psychic       NaN     3.0    59.6          0   34.0
95    96     Drowzee      Rock     Water     2.7    89.5          0   44.0
96    97       Hypno    Dragon     Grass     2.4    40.4          0   59.0
97    98      Krabby    Dragon   Psychic     0.8     8.8          0  130.0
98    99     Kingler    Poison    Dragon     2.1    59.8          0   76.0
99   100     Voltorb     Grass       NaN     2.2    27.1          0   71.0
100  101   Electrode   Psychic      Fire     2.0    29.9          0   80.0
101  102   Exeggcute     Water     Water     0.5    47.1          0  143.0
102  103   Exeggutor     Water    Flying     1.5    52.7          0   97.0
103  104      Cubone    Dragon    Flying     2.4    66.5          0   59.0
104  105     Marowak  Electric    Poison     3.5    85.0          0   21.0
105  106   Hitmonlee    Flying      Rock     2.5    91.6          0   54.5
106  107  Hitmonchan    Poison      Rock     1.1    36.6          0  116.0
107  108   Lickitung    Normal    Dragon     1.6    26.9          0   93.0
108  109     Koffing    Flying    Poison     0.4    34.9          0  147.5
109  110     Weezing      Rock      Fire     3.6    34.9          0   16.0
110  111     Rhyhorn      Rock    Normal     3.6    75.3          0   16.0
111  112      Rhydon     Grass     Grass     2.3    47.6          0   65.5
112  113     Chansey      Rock    Flying     2.6    17.5          0   50.5
113  114     Tangela      Fire    Poison     1.6    52.8          0   93.0
114  115  Kangaskhan     Grass    Flying     2.2    61.0          0   71.0
115  116      Horsea   Psychic    Flying     3.6    62.2          0   16.0
116  117      Seadra      Rock    Dragon     1.1    44.4          0  116.0
117  118     Goldeen     Grass    Dragon     1.9    17.5          0   83.5
118  119     Seaking    Poison     Water     3.6    17.9          0   16.0
119  120      Staryu    Flying      Rock     2.2    93.3          0   71.0
120  121     Starmie     Water     Water     0.4    47.9          0  147.5
121  122      MrMime      Rock      Fire     1.8    23.8          0   87.5
122  123     Scyther    Flying    Flying     2.6    28.2          0   50.5
123  124        Jynx      Fire      Rock     3.2    91.2          0   28.5
124  125  Electabuzz    Flying   Psychic     3.8    80.8          0    6.0
125  126      Magmar    Dragon      Fire     1.6    47.0          0   93.0
126  127      Pinsir     Water    Poison     1.8    82.4          0   87.5
127  128      Tauros    Flying    Normal     0.8    85.6          0  130.0
128  129    Magikarp     Water     Water     0.7    19.8          0  134.5
129  130    Gyarados     Grass     Water     3.8    47.5          0    6.0
130  131      Lapras    Poison     Grass     0.4    77.4          0  147.5
131  132       Ditto     Water     Grass     3.7    52.2          0   10.5
132  133       Eevee     Grass    Flying     2.2    98.9          0   71.0
133  134    Vaporeon   Psychic      Fire     2.3    39.6          0   65.5
134  135     Jolteon     Grass    Normal     2.4    16.5          0   59.0
135  136     Flareon     Water     Water     3.5    84.3          0   21.0
136  137     Porygon    Dragon  Electric     1.3    83.3          0  107.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0  125.0
138  139     Omastar  Electric      Rock     1.2    93.6          0  111.5
139  140      Kabuto     Water     Water     3.0    17.7          0   34.0
140  141    Kabutops      Rock     Grass     1.0    58.3          0  120.5
141  142  Aerodactyl    Poison    Poison     1.0    36.7          0  120.5
142  143     Snorlax     Grass    Normal     1.0    27.5          0  120.5
143  144    Articuno      Rock      Fire     3.9    25.2          1    2.5
144  145      Zapdos  Electric     Grass     2.7    36.7          1   44.0
145  146     Moltres    Dragon    Flying     3.3    54.6          1   25.5
146  147     Dratini      Rock    Flying     3.5    49.2          0   21.0
147  148   Dragonair    Poison     Grass     1.8    70.5          0   87.5
148  149   Dragonite    Flying   Psychic     1.3    40.1          0  107.0
149  150      Mewtwo     Water       NaN     2.9    70.6          1   37.5

In [70]:
# Method 2 — Min Method
df2["Rank"] = df2["Height"].rank(method="min" , ascending = False)
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary   Rank
0      1   Bulbasaur      Fire      Fire     2.1    91.1          0   74.0
1      2     Ivysaur     Water      Fire     1.2     6.6          0  109.0
2      3    Venusaur      Fire     Grass     1.4    17.6          0   99.0
3      4  Charmander    Flying    Dragon     1.4    29.0          0   99.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0   56.0
5      6   Charizard    Flying       NaN     2.7    33.9          0   41.0
6      7    Squirtle    Dragon      Rock     2.3    41.1          0   63.0
7      8   Wartortle      Fire   Psychic     2.7    38.5          0   41.0
8      9   Blastoise    Flying  Electric     1.1    49.3          0  115.0
9     10    Caterpie     Water  Electric     1.2    16.0          0  109.0
10    11     Metapod      Fire   Psychic     0.4    67.7          0  146.0
11    12  Butterfree      Fire       NaN     2.3    14.8          0   63.0
12    13      Weedle    Dragon       NaN     2.1    10.6          0   74.0
13    14      Kakuna    Flying      Rock     3.1    14.0          0   30.0
14    15    Beedrill  Electric    Poison     1.9    75.7          0   82.0
15    16      Pidgey    Dragon      Rock     1.4    94.8          0   99.0
16    17   Pidgeotto    Flying    Normal     1.7    33.4          0   90.0
17    18     Pidgeot     Grass       NaN     2.9    50.5          0   37.0
18    19     Rattata      Fire  Electric     2.0    88.7          0   79.0
19    20    Raticate    Dragon     Grass     0.8    31.4          0  127.0
20    21     Spearow      Rock    Normal     3.6    63.3          0   14.0
21    22      Fearow    Poison    Poison     2.1    92.3          0   74.0
22    23       Ekans      Rock    Poison     3.0    55.4          0   32.0
23    24       Arbok   Psychic      Fire     0.5    83.9          0  141.0
24    25     Pikachu    Poison    Poison     2.3    13.2          0   63.0
25    26      Raichu   Psychic    Poison     3.3    98.6          0   24.0
26    27   Sandshrew  Electric   Psychic     2.8    46.8          0   39.0
27    28   Sandslash    Dragon    Poison     3.3    67.0          0   24.0
28    29    NidoranF   Psychic      Rock     3.5    89.4          0   19.0
29    30    Nidorina   Psychic      Fire     0.5    93.5          0  141.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0   24.0
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0   54.0
32    33    Nidorino   Psychic    Dragon     0.6    19.7          0  136.0
33    34    Nidoking     Water     Water     0.6    68.3          0  136.0
34    35    Clefairy    Normal    Flying     0.5    48.1          0  141.0
35    36    Clefable     Water     Grass     2.6    51.0          0   48.0
36    37      Vulpix      Rock     Grass     0.9    68.0          0  124.0
37    38   Ninetales  Electric       NaN     1.0    45.4          0  118.0
38    39  Jigglypuff    Poison     Water     0.6     2.0          0  136.0
39    40  Wigglytuff     Grass      Fire     3.5     6.3          0   19.0
40    41       Zubat    Poison      Fire     1.4    78.5          0   99.0
41    42      Golbat   Psychic    Poison     2.3    19.4          0   63.0
42    43      Oddish     Water      Rock     3.7    13.4          0    8.0
43    44       Gloom      Fire    Flying     3.7     2.3          0    8.0
44    45   Vileplume    Flying    Normal     1.5    43.1          0   96.0
45    46       Paras    Normal      Rock     1.9    70.6          0   82.0
46    47    Parasect    Flying      Rock     1.3    90.0          0  106.0
47    48     Venonat  Electric  Electric     2.0    81.7          0   79.0
48    49    Venomoth    Normal    Normal     2.8    78.6          0   39.0
49    50     Diglett    Normal     Water     2.4     4.5          0   56.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  134.0
51    52      Meowth   Psychic     Grass     3.7    41.4          0    8.0
52    53     Persian      Fire  Electric     0.6    49.5          0  136.0
53    54     Psyduck     Grass       NaN     2.6     9.1          0   48.0
54    55     Golduck    Dragon  Electric     1.0    14.8          0  118.0
55    56      Mankey      Rock       NaN     0.3    29.0          0  150.0
56    57    Primeape   Psychic    Poison     1.9     3.5          0   82.0
57    58   Growlithe    Normal     Water     3.8    49.3          0    5.0
58    59    Arcanine    Flying    Normal     0.9    92.8          0  124.0
59    60     Poliwag     Water    Dragon     1.8    39.7          0   86.0
60    61   Poliwhirl    Normal      Rock     1.5    43.2          0   96.0
61    62   Poliwrath    Poison      Fire     2.4    69.2          0   56.0
62    63        Abra      Fire      Rock     0.5    28.5          0  141.0
63    64     Kadabra    Dragon    Flying     3.2    69.3          0   28.0
64    65    Alakazam    Flying    Normal     0.8    11.5          0  127.0
65    66      Machop    Dragon     Water     3.0    56.1          0   32.0
66    67     Machoke    Poison      Rock     3.9    55.7          0    1.0
67    68     Machamp    Flying    Poison     0.8    66.8          0  127.0
68    69  Bellsprout   Psychic  Electric     1.6    16.3          0   91.0
69    70  Weepinbell  Electric    Poison     1.4    10.2          0   99.0
70    71  Victreebel    Poison       NaN     2.6    37.0          0   48.0
71    72   Tentacool     Grass   Psychic     0.8     8.0          0  127.0
72    73  Tentacruel      Fire    Poison     3.9    53.6          0    1.0
73    74     Geodude    Dragon    Flying     0.6    84.2          0  136.0
74    75    Graveler    Normal    Dragon     1.4    17.3          0   99.0
75    76       Golem    Flying     Grass     3.1    68.2          0   30.0
76    77      Ponyta    Dragon   Psychic     1.4    74.6          0   99.0
77    78    Rapidash     Water   Psychic     2.6    69.5          0   48.0
78    79    Slowpoke    Normal      Fire     3.0    41.9          0   32.0
79    80     Slowbro     Water   Psychic     2.2    55.3          0   69.0
80    81   Magnemite     Grass    Flying     1.2    53.1          0  109.0
81    82    Magneton     Grass  Electric     2.7    58.9          0   41.0
82    83   Farfetchd     Water     Water     1.0    86.6          0  118.0
83    84       Doduo     Water    Normal     2.1    33.7          0   74.0
84    85      Dodrio     Water    Normal     3.7    21.2          0    8.0
85    86        Seel    Flying      Fire     2.7    77.4          0   41.0
86    87     Dewgong  Electric     Grass     2.4    67.0          0   56.0
87    88      Grimer   Psychic      Rock     3.9    25.8          0    1.0
88    89         Muk  Electric       NaN     0.8    33.1          0  127.0
89    90    Shellder      Rock  Electric     1.2    84.9          0  109.0
90    91    Cloyster    Dragon  Electric     1.2    80.6          0  109.0
91    92      Gastly    Normal  Electric     2.7    93.2          0   41.0
92    93     Haunter    Flying  Electric     3.7     2.2          0    8.0
93    94      Gengar      Fire    Normal     1.6    76.2          0   91.0
94    95        Onix   Psychic       NaN     3.0    59.6          0   32.0
95    96     Drowzee      Rock     Water     2.7    89.5          0   41.0
96    97       Hypno    Dragon     Grass     2.4    40.4          0   56.0
97    98      Krabby    Dragon   Psychic     0.8     8.8          0  127.0
98    99     Kingler    Poison    Dragon     2.1    59.8          0   74.0
99   100     Voltorb     Grass       NaN     2.2    27.1          0   69.0
100  101   Electrode   Psychic      Fire     2.0    29.9          0   79.0
101  102   Exeggcute     Water     Water     0.5    47.1          0  141.0
102  103   Exeggutor     Water    Flying     1.5    52.7          0   96.0
103  104      Cubone    Dragon    Flying     2.4    66.5          0   56.0
104  105     Marowak  Electric    Poison     3.5    85.0          0   19.0
105  106   Hitmonlee    Flying      Rock     2.5    91.6          0   54.0
106  107  Hitmonchan    Poison      Rock     1.1    36.6          0  115.0
107  108   Lickitung    Normal    Dragon     1.6    26.9          0   91.0
108  109     Koffing    Flying    Poison     0.4    34.9          0  146.0
109  110     Weezing      Rock      Fire     3.6    34.9          0   14.0
110  111     Rhyhorn      Rock    Normal     3.6    75.3          0   14.0
111  112      Rhydon     Grass     Grass     2.3    47.6          0   63.0
112  113     Chansey      Rock    Flying     2.6    17.5          0   48.0
113  114     Tangela      Fire    Poison     1.6    52.8          0   91.0
114  115  Kangaskhan     Grass    Flying     2.2    61.0          0   69.0
115  116      Horsea   Psychic    Flying     3.6    62.2          0   14.0
116  117      Seadra      Rock    Dragon     1.1    44.4          0  115.0
117  118     Goldeen     Grass    Dragon     1.9    17.5          0   82.0
118  119     Seaking    Poison     Water     3.6    17.9          0   14.0
119  120      Staryu    Flying      Rock     2.2    93.3          0   69.0
120  121     Starmie     Water     Water     0.4    47.9          0  146.0
121  122      MrMime      Rock      Fire     1.8    23.8          0   86.0
122  123     Scyther    Flying    Flying     2.6    28.2          0   48.0
123  124        Jynx      Fire      Rock     3.2    91.2          0   28.0
124  125  Electabuzz    Flying   Psychic     3.8    80.8          0    5.0
125  126      Magmar    Dragon      Fire     1.6    47.0          0   91.0
126  127      Pinsir     Water    Poison     1.8    82.4          0   86.0
127  128      Tauros    Flying    Normal     0.8    85.6          0  127.0
128  129    Magikarp     Water     Water     0.7    19.8          0  134.0
129  130    Gyarados     Grass     Water     3.8    47.5          0    5.0
130  131      Lapras    Poison     Grass     0.4    77.4          0  146.0
131  132       Ditto     Water     Grass     3.7    52.2          0    8.0
132  133       Eevee     Grass    Flying     2.2    98.9          0   69.0
133  134    Vaporeon   Psychic      Fire     2.3    39.6          0   63.0
134  135     Jolteon     Grass    Normal     2.4    16.5          0   56.0
135  136     Flareon     Water     Water     3.5    84.3          0   19.0
136  137     Porygon    Dragon  Electric     1.3    83.3          0  106.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0  124.0
138  139     Omastar  Electric      Rock     1.2    93.6          0  109.0
139  140      Kabuto     Water     Water     3.0    17.7          0   32.0
140  141    Kabutops      Rock     Grass     1.0    58.3          0  118.0
141  142  Aerodactyl    Poison    Poison     1.0    36.7          0  118.0
142  143     Snorlax     Grass    Normal     1.0    27.5          0  118.0
143  144    Articuno      Rock      Fire     3.9    25.2          1    1.0
144  145      Zapdos  Electric     Grass     2.7    36.7          1   41.0
145  146     Moltres    Dragon    Flying     3.3    54.6          1   24.0
146  147     Dratini      Rock    Flying     3.5    49.2          0   19.0
147  148   Dragonair    Poison     Grass     1.8    70.5          0   86.0
148  149   Dragonite    Flying   Psychic     1.3    40.1          0  106.0
149  150      Mewtwo     Water       NaN     2.9    70.6          1   37.0

In [71]:
# Method 2 — Max Method
df2["Rank"] = df2["Height"].rank(method="max" , ascending = False)
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary   Rank
0      1   Bulbasaur      Fire      Fire     2.1    91.1          0   78.0
1      2     Ivysaur     Water      Fire     1.2     6.6          0  114.0
2      3    Venusaur      Fire     Grass     1.4    17.6          0  105.0
3      4  Charmander    Flying    Dragon     1.4    29.0          0  105.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0   62.0
5      6   Charizard    Flying       NaN     2.7    33.9          0   47.0
6      7    Squirtle    Dragon      Rock     2.3    41.1          0   68.0
7      8   Wartortle      Fire   Psychic     2.7    38.5          0   47.0
8      9   Blastoise    Flying  Electric     1.1    49.3          0  117.0
9     10    Caterpie     Water  Electric     1.2    16.0          0  114.0
10    11     Metapod      Fire   Psychic     0.4    67.7          0  149.0
11    12  Butterfree      Fire       NaN     2.3    14.8          0   68.0
12    13      Weedle    Dragon       NaN     2.1    10.6          0   78.0
13    14      Kakuna    Flying      Rock     3.1    14.0          0   31.0
14    15    Beedrill  Electric    Poison     1.9    75.7          0   85.0
15    16      Pidgey    Dragon      Rock     1.4    94.8          0  105.0
16    17   Pidgeotto    Flying    Normal     1.7    33.4          0   90.0
17    18     Pidgeot     Grass       NaN     2.9    50.5          0   38.0
18    19     Rattata      Fire  Electric     2.0    88.7          0   81.0
19    20    Raticate    Dragon     Grass     0.8    31.4          0  133.0
20    21     Spearow      Rock    Normal     3.6    63.3          0   18.0
21    22      Fearow    Poison    Poison     2.1    92.3          0   78.0
22    23       Ekans      Rock    Poison     3.0    55.4          0   36.0
23    24       Arbok   Psychic      Fire     0.5    83.9          0  145.0
24    25     Pikachu    Poison    Poison     2.3    13.2          0   68.0
25    26      Raichu   Psychic    Poison     3.3    98.6          0   27.0
26    27   Sandshrew  Electric   Psychic     2.8    46.8          0   40.0
27    28   Sandslash    Dragon    Poison     3.3    67.0          0   27.0
28    29    NidoranF   Psychic      Rock     3.5    89.4          0   23.0
29    30    Nidorina   Psychic      Fire     0.5    93.5          0  145.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0   27.0
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0   55.0
32    33    Nidorino   Psychic    Dragon     0.6    19.7          0  140.0
33    34    Nidoking     Water     Water     0.6    68.3          0  140.0
34    35    Clefairy    Normal    Flying     0.5    48.1          0  145.0
35    36    Clefable     Water     Grass     2.6    51.0          0   53.0
36    37      Vulpix      Rock     Grass     0.9    68.0          0  126.0
37    38   Ninetales  Electric       NaN     1.0    45.4          0  123.0
38    39  Jigglypuff    Poison     Water     0.6     2.0          0  140.0
39    40  Wigglytuff     Grass      Fire     3.5     6.3          0   23.0
40    41       Zubat    Poison      Fire     1.4    78.5          0  105.0
41    42      Golbat   Psychic    Poison     2.3    19.4          0   68.0
42    43      Oddish     Water      Rock     3.7    13.4          0   13.0
43    44       Gloom      Fire    Flying     3.7     2.3          0   13.0
44    45   Vileplume    Flying    Normal     1.5    43.1          0   98.0
45    46       Paras    Normal      Rock     1.9    70.6          0   85.0
46    47    Parasect    Flying      Rock     1.3    90.0          0  108.0
47    48     Venonat  Electric  Electric     2.0    81.7          0   81.0
48    49    Venomoth    Normal    Normal     2.8    78.6          0   40.0
49    50     Diglett    Normal     Water     2.4     4.5          0   62.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  135.0
51    52      Meowth   Psychic     Grass     3.7    41.4          0   13.0
52    53     Persian      Fire  Electric     0.6    49.5          0  140.0
53    54     Psyduck     Grass       NaN     2.6     9.1          0   53.0
54    55     Golduck    Dragon  Electric     1.0    14.8          0  123.0
55    56      Mankey      Rock       NaN     0.3    29.0          0  150.0
56    57    Primeape   Psychic    Poison     1.9     3.5          0   85.0
57    58   Growlithe    Normal     Water     3.8    49.3          0    7.0
58    59    Arcanine    Flying    Normal     0.9    92.8          0  126.0
59    60     Poliwag     Water    Dragon     1.8    39.7          0   89.0
60    61   Poliwhirl    Normal      Rock     1.5    43.2          0   98.0
61    62   Poliwrath    Poison      Fire     2.4    69.2          0   62.0
62    63        Abra      Fire      Rock     0.5    28.5          0  145.0
63    64     Kadabra    Dragon    Flying     3.2    69.3          0   29.0
64    65    Alakazam    Flying    Normal     0.8    11.5          0  133.0
65    66      Machop    Dragon     Water     3.0    56.1          0   36.0
66    67     Machoke    Poison      Rock     3.9    55.7          0    4.0
67    68     Machamp    Flying    Poison     0.8    66.8          0  133.0
68    69  Bellsprout   Psychic  Electric     1.6    16.3          0   95.0
69    70  Weepinbell  Electric    Poison     1.4    10.2          0  105.0
70    71  Victreebel    Poison       NaN     2.6    37.0          0   53.0
71    72   Tentacool     Grass   Psychic     0.8     8.0          0  133.0
72    73  Tentacruel      Fire    Poison     3.9    53.6          0    4.0
73    74     Geodude    Dragon    Flying     0.6    84.2          0  140.0
74    75    Graveler    Normal    Dragon     1.4    17.3          0  105.0
75    76       Golem    Flying     Grass     3.1    68.2          0   31.0
76    77      Ponyta    Dragon   Psychic     1.4    74.6          0  105.0
77    78    Rapidash     Water   Psychic     2.6    69.5          0   53.0
78    79    Slowpoke    Normal      Fire     3.0    41.9          0   36.0
79    80     Slowbro     Water   Psychic     2.2    55.3          0   73.0
80    81   Magnemite     Grass    Flying     1.2    53.1          0  114.0
81    82    Magneton     Grass  Electric     2.7    58.9          0   47.0
82    83   Farfetchd     Water     Water     1.0    86.6          0  123.0
83    84       Doduo     Water    Normal     2.1    33.7          0   78.0
84    85      Dodrio     Water    Normal     3.7    21.2          0   13.0
85    86        Seel    Flying      Fire     2.7    77.4          0   47.0
86    87     Dewgong  Electric     Grass     2.4    67.0          0   62.0
87    88      Grimer   Psychic      Rock     3.9    25.8          0    4.0
88    89         Muk  Electric       NaN     0.8    33.1          0  133.0
89    90    Shellder      Rock  Electric     1.2    84.9          0  114.0
90    91    Cloyster    Dragon  Electric     1.2    80.6          0  114.0
91    92      Gastly    Normal  Electric     2.7    93.2          0   47.0
92    93     Haunter    Flying  Electric     3.7     2.2          0   13.0
93    94      Gengar      Fire    Normal     1.6    76.2          0   95.0
94    95        Onix   Psychic       NaN     3.0    59.6          0   36.0
95    96     Drowzee      Rock     Water     2.7    89.5          0   47.0
96    97       Hypno    Dragon     Grass     2.4    40.4          0   62.0
97    98      Krabby    Dragon   Psychic     0.8     8.8          0  133.0
98    99     Kingler    Poison    Dragon     2.1    59.8          0   78.0
99   100     Voltorb     Grass       NaN     2.2    27.1          0   73.0
100  101   Electrode   Psychic      Fire     2.0    29.9          0   81.0
101  102   Exeggcute     Water     Water     0.5    47.1          0  145.0
102  103   Exeggutor     Water    Flying     1.5    52.7          0   98.0
103  104      Cubone    Dragon    Flying     2.4    66.5          0   62.0
104  105     Marowak  Electric    Poison     3.5    85.0          0   23.0
105  106   Hitmonlee    Flying      Rock     2.5    91.6          0   55.0
106  107  Hitmonchan    Poison      Rock     1.1    36.6          0  117.0
107  108   Lickitung    Normal    Dragon     1.6    26.9          0   95.0
108  109     Koffing    Flying    Poison     0.4    34.9          0  149.0
109  110     Weezing      Rock      Fire     3.6    34.9          0   18.0
110  111     Rhyhorn      Rock    Normal     3.6    75.3          0   18.0
111  112      Rhydon     Grass     Grass     2.3    47.6          0   68.0
112  113     Chansey      Rock    Flying     2.6    17.5          0   53.0
113  114     Tangela      Fire    Poison     1.6    52.8          0   95.0
114  115  Kangaskhan     Grass    Flying     2.2    61.0          0   73.0
115  116      Horsea   Psychic    Flying     3.6    62.2          0   18.0
116  117      Seadra      Rock    Dragon     1.1    44.4          0  117.0
117  118     Goldeen     Grass    Dragon     1.9    17.5          0   85.0
118  119     Seaking    Poison     Water     3.6    17.9          0   18.0
119  120      Staryu    Flying      Rock     2.2    93.3          0   73.0
120  121     Starmie     Water     Water     0.4    47.9          0  149.0
121  122      MrMime      Rock      Fire     1.8    23.8          0   89.0
122  123     Scyther    Flying    Flying     2.6    28.2          0   53.0
123  124        Jynx      Fire      Rock     3.2    91.2          0   29.0
124  125  Electabuzz    Flying   Psychic     3.8    80.8          0    7.0
125  126      Magmar    Dragon      Fire     1.6    47.0          0   95.0
126  127      Pinsir     Water    Poison     1.8    82.4          0   89.0
127  128      Tauros    Flying    Normal     0.8    85.6          0  133.0
128  129    Magikarp     Water     Water     0.7    19.8          0  135.0
129  130    Gyarados     Grass     Water     3.8    47.5          0    7.0
130  131      Lapras    Poison     Grass     0.4    77.4          0  149.0
131  132       Ditto     Water     Grass     3.7    52.2          0   13.0
132  133       Eevee     Grass    Flying     2.2    98.9          0   73.0
133  134    Vaporeon   Psychic      Fire     2.3    39.6          0   68.0
134  135     Jolteon     Grass    Normal     2.4    16.5          0   62.0
135  136     Flareon     Water     Water     3.5    84.3          0   23.0
136  137     Porygon    Dragon  Electric     1.3    83.3          0  108.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0  126.0
138  139     Omastar  Electric      Rock     1.2    93.6          0  114.0
139  140      Kabuto     Water     Water     3.0    17.7          0   36.0
140  141    Kabutops      Rock     Grass     1.0    58.3          0  123.0
141  142  Aerodactyl    Poison    Poison     1.0    36.7          0  123.0
142  143     Snorlax     Grass    Normal     1.0    27.5          0  123.0
143  144    Articuno      Rock      Fire     3.9    25.2          1    4.0
144  145      Zapdos  Electric     Grass     2.7    36.7          1   47.0
145  146     Moltres    Dragon    Flying     3.3    54.6          1   27.0
146  147     Dratini      Rock    Flying     3.5    49.2          0   23.0
147  148   Dragonair    Poison     Grass     1.8    70.5          0   89.0
148  149   Dragonite    Flying   Psychic     1.3    40.1          0  108.0
149  150      Mewtwo     Water       NaN     2.9    70.6          1   38.0

In [72]:
# Method 4 — first
# Ranks based on appearance order.
df2["Rank"] = df2["Height"].rank(method="first" , ascending = False)
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary   Rank
0      1   Bulbasaur      Fire      Fire     2.1    91.1          0   74.0
1      2     Ivysaur     Water      Fire     1.2     6.6          0  109.0
2      3    Venusaur      Fire     Grass     1.4    17.6          0   99.0
3      4  Charmander    Flying    Dragon     1.4    29.0          0  100.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0   56.0
5      6   Charizard    Flying       NaN     2.7    33.9          0   41.0
6      7    Squirtle    Dragon      Rock     2.3    41.1          0   63.0
7      8   Wartortle      Fire   Psychic     2.7    38.5          0   42.0
8      9   Blastoise    Flying  Electric     1.1    49.3          0  115.0
9     10    Caterpie     Water  Electric     1.2    16.0          0  110.0
10    11     Metapod      Fire   Psychic     0.4    67.7          0  146.0
11    12  Butterfree      Fire       NaN     2.3    14.8          0   64.0
12    13      Weedle    Dragon       NaN     2.1    10.6          0   75.0
13    14      Kakuna    Flying      Rock     3.1    14.0          0   30.0
14    15    Beedrill  Electric    Poison     1.9    75.7          0   82.0
15    16      Pidgey    Dragon      Rock     1.4    94.8          0  101.0
16    17   Pidgeotto    Flying    Normal     1.7    33.4          0   90.0
17    18     Pidgeot     Grass       NaN     2.9    50.5          0   37.0
18    19     Rattata      Fire  Electric     2.0    88.7          0   79.0
19    20    Raticate    Dragon     Grass     0.8    31.4          0  127.0
20    21     Spearow      Rock    Normal     3.6    63.3          0   14.0
21    22      Fearow    Poison    Poison     2.1    92.3          0   76.0
22    23       Ekans      Rock    Poison     3.0    55.4          0   32.0
23    24       Arbok   Psychic      Fire     0.5    83.9          0  141.0
24    25     Pikachu    Poison    Poison     2.3    13.2          0   65.0
25    26      Raichu   Psychic    Poison     3.3    98.6          0   24.0
26    27   Sandshrew  Electric   Psychic     2.8    46.8          0   39.0
27    28   Sandslash    Dragon    Poison     3.3    67.0          0   25.0
28    29    NidoranF   Psychic      Rock     3.5    89.4          0   19.0
29    30    Nidorina   Psychic      Fire     0.5    93.5          0  142.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0   26.0
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0   54.0
32    33    Nidorino   Psychic    Dragon     0.6    19.7          0  136.0
33    34    Nidoking     Water     Water     0.6    68.3          0  137.0
34    35    Clefairy    Normal    Flying     0.5    48.1          0  143.0
35    36    Clefable     Water     Grass     2.6    51.0          0   48.0
36    37      Vulpix      Rock     Grass     0.9    68.0          0  124.0
37    38   Ninetales  Electric       NaN     1.0    45.4          0  118.0
38    39  Jigglypuff    Poison     Water     0.6     2.0          0  138.0
39    40  Wigglytuff     Grass      Fire     3.5     6.3          0   20.0
40    41       Zubat    Poison      Fire     1.4    78.5          0  102.0
41    42      Golbat   Psychic    Poison     2.3    19.4          0   66.0
42    43      Oddish     Water      Rock     3.7    13.4          0    8.0
43    44       Gloom      Fire    Flying     3.7     2.3          0    9.0
44    45   Vileplume    Flying    Normal     1.5    43.1          0   96.0
45    46       Paras    Normal      Rock     1.9    70.6          0   83.0
46    47    Parasect    Flying      Rock     1.3    90.0          0  106.0
47    48     Venonat  Electric  Electric     2.0    81.7          0   80.0
48    49    Venomoth    Normal    Normal     2.8    78.6          0   40.0
49    50     Diglett    Normal     Water     2.4     4.5          0   57.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  134.0
51    52      Meowth   Psychic     Grass     3.7    41.4          0   10.0
52    53     Persian      Fire  Electric     0.6    49.5          0  139.0
53    54     Psyduck     Grass       NaN     2.6     9.1          0   49.0
54    55     Golduck    Dragon  Electric     1.0    14.8          0  119.0
55    56      Mankey      Rock       NaN     0.3    29.0          0  150.0
56    57    Primeape   Psychic    Poison     1.9     3.5          0   84.0
57    58   Growlithe    Normal     Water     3.8    49.3          0    5.0
58    59    Arcanine    Flying    Normal     0.9    92.8          0  125.0
59    60     Poliwag     Water    Dragon     1.8    39.7          0   86.0
60    61   Poliwhirl    Normal      Rock     1.5    43.2          0   97.0
61    62   Poliwrath    Poison      Fire     2.4    69.2          0   58.0
62    63        Abra      Fire      Rock     0.5    28.5          0  144.0
63    64     Kadabra    Dragon    Flying     3.2    69.3          0   28.0
64    65    Alakazam    Flying    Normal     0.8    11.5          0  128.0
65    66      Machop    Dragon     Water     3.0    56.1          0   33.0
66    67     Machoke    Poison      Rock     3.9    55.7          0    1.0
67    68     Machamp    Flying    Poison     0.8    66.8          0  129.0
68    69  Bellsprout   Psychic  Electric     1.6    16.3          0   91.0
69    70  Weepinbell  Electric    Poison     1.4    10.2          0  103.0
70    71  Victreebel    Poison       NaN     2.6    37.0          0   50.0
71    72   Tentacool     Grass   Psychic     0.8     8.0          0  130.0
72    73  Tentacruel      Fire    Poison     3.9    53.6          0    2.0
73    74     Geodude    Dragon    Flying     0.6    84.2          0  140.0
74    75    Graveler    Normal    Dragon     1.4    17.3          0  104.0
75    76       Golem    Flying     Grass     3.1    68.2          0   31.0
76    77      Ponyta    Dragon   Psychic     1.4    74.6          0  105.0
77    78    Rapidash     Water   Psychic     2.6    69.5          0   51.0
78    79    Slowpoke    Normal      Fire     3.0    41.9          0   34.0
79    80     Slowbro     Water   Psychic     2.2    55.3          0   69.0
80    81   Magnemite     Grass    Flying     1.2    53.1          0  111.0
81    82    Magneton     Grass  Electric     2.7    58.9          0   43.0
82    83   Farfetchd     Water     Water     1.0    86.6          0  120.0
83    84       Doduo     Water    Normal     2.1    33.7          0   77.0
84    85      Dodrio     Water    Normal     3.7    21.2          0   11.0
85    86        Seel    Flying      Fire     2.7    77.4          0   44.0
86    87     Dewgong  Electric     Grass     2.4    67.0          0   59.0
87    88      Grimer   Psychic      Rock     3.9    25.8          0    3.0
88    89         Muk  Electric       NaN     0.8    33.1          0  131.0
89    90    Shellder      Rock  Electric     1.2    84.9          0  112.0
90    91    Cloyster    Dragon  Electric     1.2    80.6          0  113.0
91    92      Gastly    Normal  Electric     2.7    93.2          0   45.0
92    93     Haunter    Flying  Electric     3.7     2.2          0   12.0
93    94      Gengar      Fire    Normal     1.6    76.2          0   92.0
94    95        Onix   Psychic       NaN     3.0    59.6          0   35.0
95    96     Drowzee      Rock     Water     2.7    89.5          0   46.0
96    97       Hypno    Dragon     Grass     2.4    40.4          0   60.0
97    98      Krabby    Dragon   Psychic     0.8     8.8          0  132.0
98    99     Kingler    Poison    Dragon     2.1    59.8          0   78.0
99   100     Voltorb     Grass       NaN     2.2    27.1          0   70.0
100  101   Electrode   Psychic      Fire     2.0    29.9          0   81.0
101  102   Exeggcute     Water     Water     0.5    47.1          0  145.0
102  103   Exeggutor     Water    Flying     1.5    52.7          0   98.0
103  104      Cubone    Dragon    Flying     2.4    66.5          0   61.0
104  105     Marowak  Electric    Poison     3.5    85.0          0   21.0
105  106   Hitmonlee    Flying      Rock     2.5    91.6          0   55.0
106  107  Hitmonchan    Poison      Rock     1.1    36.6          0  116.0
107  108   Lickitung    Normal    Dragon     1.6    26.9          0   93.0
108  109     Koffing    Flying    Poison     0.4    34.9          0  147.0
109  110     Weezing      Rock      Fire     3.6    34.9          0   15.0
110  111     Rhyhorn      Rock    Normal     3.6    75.3          0   16.0
111  112      Rhydon     Grass     Grass     2.3    47.6          0   67.0
112  113     Chansey      Rock    Flying     2.6    17.5          0   52.0
113  114     Tangela      Fire    Poison     1.6    52.8          0   94.0
114  115  Kangaskhan     Grass    Flying     2.2    61.0          0   71.0
115  116      Horsea   Psychic    Flying     3.6    62.2          0   17.0
116  117      Seadra      Rock    Dragon     1.1    44.4          0  117.0
117  118     Goldeen     Grass    Dragon     1.9    17.5          0   85.0
118  119     Seaking    Poison     Water     3.6    17.9          0   18.0
119  120      Staryu    Flying      Rock     2.2    93.3          0   72.0
120  121     Starmie     Water     Water     0.4    47.9          0  148.0
121  122      MrMime      Rock      Fire     1.8    23.8          0   87.0
122  123     Scyther    Flying    Flying     2.6    28.2          0   53.0
123  124        Jynx      Fire      Rock     3.2    91.2          0   29.0
124  125  Electabuzz    Flying   Psychic     3.8    80.8          0    6.0
125  126      Magmar    Dragon      Fire     1.6    47.0          0   95.0
126  127      Pinsir     Water    Poison     1.8    82.4          0   88.0
127  128      Tauros    Flying    Normal     0.8    85.6          0  133.0
128  129    Magikarp     Water     Water     0.7    19.8          0  135.0
129  130    Gyarados     Grass     Water     3.8    47.5          0    7.0
130  131      Lapras    Poison     Grass     0.4    77.4          0  149.0
131  132       Ditto     Water     Grass     3.7    52.2          0   13.0
132  133       Eevee     Grass    Flying     2.2    98.9          0   73.0
133  134    Vaporeon   Psychic      Fire     2.3    39.6          0   68.0
134  135     Jolteon     Grass    Normal     2.4    16.5          0   62.0
135  136     Flareon     Water     Water     3.5    84.3          0   22.0
136  137     Porygon    Dragon  Electric     1.3    83.3          0  107.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0  126.0
138  139     Omastar  Electric      Rock     1.2    93.6          0  114.0
139  140      Kabuto     Water     Water     3.0    17.7          0   36.0
140  141    Kabutops      Rock     Grass     1.0    58.3          0  121.0
141  142  Aerodactyl    Poison    Poison     1.0    36.7          0  122.0
142  143     Snorlax     Grass    Normal     1.0    27.5          0  123.0
143  144    Articuno      Rock      Fire     3.9    25.2          1    4.0
144  145      Zapdos  Electric     Grass     2.7    36.7          1   47.0
145  146     Moltres    Dragon    Flying     3.3    54.6          1   27.0
146  147     Dratini      Rock    Flying     3.5    49.2          0   23.0
147  148   Dragonair    Poison     Grass     1.8    70.5          0   89.0
148  149   Dragonite    Flying   Psychic     1.3    40.1          0  108.0
149  150      Mewtwo     Water       NaN     2.9    70.6          1   38.0

In [73]:
# Method 5 — dense
# Main Rule of Dense Ranking
# Duplicate values get same rank
# AND
# Next rank increases by only 1
# No gaps.
    
df2["Rank"] = df2["Height"].rank(method="dense" , ascending = False)
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary  Rank
0      1   Bulbasaur      Fire      Fire     2.1    91.1          0  18.0
1      2     Ivysaur     Water      Fire     1.2     6.6          0  27.0
2      3    Venusaur      Fire     Grass     1.4    17.6          0  25.0
3      4  Charmander    Flying    Dragon     1.4    29.0          0  25.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0  15.0
5      6   Charizard    Flying       NaN     2.7    33.9          0  12.0
6      7    Squirtle    Dragon      Rock     2.3    41.1          0  16.0
7      8   Wartortle      Fire   Psychic     2.7    38.5          0  12.0
8      9   Blastoise    Flying  Electric     1.1    49.3          0  28.0
9     10    Caterpie     Water  Electric     1.2    16.0          0  27.0
10    11     Metapod      Fire   Psychic     0.4    67.7          0  35.0
11    12  Butterfree      Fire       NaN     2.3    14.8          0  16.0
12    13      Weedle    Dragon       NaN     2.1    10.6          0  18.0
13    14      Kakuna    Flying      Rock     3.1    14.0          0   8.0
14    15    Beedrill  Electric    Poison     1.9    75.7          0  20.0
15    16      Pidgey    Dragon      Rock     1.4    94.8          0  25.0
16    17   Pidgeotto    Flying    Normal     1.7    33.4          0  22.0
17    18     Pidgeot     Grass       NaN     2.9    50.5          0  10.0
18    19     Rattata      Fire  Electric     2.0    88.7          0  19.0
19    20    Raticate    Dragon     Grass     0.8    31.4          0  31.0
20    21     Spearow      Rock    Normal     3.6    63.3          0   4.0
21    22      Fearow    Poison    Poison     2.1    92.3          0  18.0
22    23       Ekans      Rock    Poison     3.0    55.4          0   9.0
23    24       Arbok   Psychic      Fire     0.5    83.9          0  34.0
24    25     Pikachu    Poison    Poison     2.3    13.2          0  16.0
25    26      Raichu   Psychic    Poison     3.3    98.6          0   6.0
26    27   Sandshrew  Electric   Psychic     2.8    46.8          0  11.0
27    28   Sandslash    Dragon    Poison     3.3    67.0          0   6.0
28    29    NidoranF   Psychic      Rock     3.5    89.4          0   5.0
29    30    Nidorina   Psychic      Fire     0.5    93.5          0  34.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0   6.0
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0  14.0
32    33    Nidorino   Psychic    Dragon     0.6    19.7          0  33.0
33    34    Nidoking     Water     Water     0.6    68.3          0  33.0
34    35    Clefairy    Normal    Flying     0.5    48.1          0  34.0
35    36    Clefable     Water     Grass     2.6    51.0          0  13.0
36    37      Vulpix      Rock     Grass     0.9    68.0          0  30.0
37    38   Ninetales  Electric       NaN     1.0    45.4          0  29.0
38    39  Jigglypuff    Poison     Water     0.6     2.0          0  33.0
39    40  Wigglytuff     Grass      Fire     3.5     6.3          0   5.0
40    41       Zubat    Poison      Fire     1.4    78.5          0  25.0
41    42      Golbat   Psychic    Poison     2.3    19.4          0  16.0
42    43      Oddish     Water      Rock     3.7    13.4          0   3.0
43    44       Gloom      Fire    Flying     3.7     2.3          0   3.0
44    45   Vileplume    Flying    Normal     1.5    43.1          0  24.0
45    46       Paras    Normal      Rock     1.9    70.6          0  20.0
46    47    Parasect    Flying      Rock     1.3    90.0          0  26.0
47    48     Venonat  Electric  Electric     2.0    81.7          0  19.0
48    49    Venomoth    Normal    Normal     2.8    78.6          0  11.0
49    50     Diglett    Normal     Water     2.4     4.5          0  15.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  32.0
51    52      Meowth   Psychic     Grass     3.7    41.4          0   3.0
52    53     Persian      Fire  Electric     0.6    49.5          0  33.0
53    54     Psyduck     Grass       NaN     2.6     9.1          0  13.0
54    55     Golduck    Dragon  Electric     1.0    14.8          0  29.0
55    56      Mankey      Rock       NaN     0.3    29.0          0  36.0
56    57    Primeape   Psychic    Poison     1.9     3.5          0  20.0
57    58   Growlithe    Normal     Water     3.8    49.3          0   2.0
58    59    Arcanine    Flying    Normal     0.9    92.8          0  30.0
59    60     Poliwag     Water    Dragon     1.8    39.7          0  21.0
60    61   Poliwhirl    Normal      Rock     1.5    43.2          0  24.0
61    62   Poliwrath    Poison      Fire     2.4    69.2          0  15.0
62    63        Abra      Fire      Rock     0.5    28.5          0  34.0
63    64     Kadabra    Dragon    Flying     3.2    69.3          0   7.0
64    65    Alakazam    Flying    Normal     0.8    11.5          0  31.0
65    66      Machop    Dragon     Water     3.0    56.1          0   9.0
66    67     Machoke    Poison      Rock     3.9    55.7          0   1.0
67    68     Machamp    Flying    Poison     0.8    66.8          0  31.0
68    69  Bellsprout   Psychic  Electric     1.6    16.3          0  23.0
69    70  Weepinbell  Electric    Poison     1.4    10.2          0  25.0
70    71  Victreebel    Poison       NaN     2.6    37.0          0  13.0
71    72   Tentacool     Grass   Psychic     0.8     8.0          0  31.0
72    73  Tentacruel      Fire    Poison     3.9    53.6          0   1.0
73    74     Geodude    Dragon    Flying     0.6    84.2          0  33.0
74    75    Graveler    Normal    Dragon     1.4    17.3          0  25.0
75    76       Golem    Flying     Grass     3.1    68.2          0   8.0
76    77      Ponyta    Dragon   Psychic     1.4    74.6          0  25.0
77    78    Rapidash     Water   Psychic     2.6    69.5          0  13.0
78    79    Slowpoke    Normal      Fire     3.0    41.9          0   9.0
79    80     Slowbro     Water   Psychic     2.2    55.3          0  17.0
80    81   Magnemite     Grass    Flying     1.2    53.1          0  27.0
81    82    Magneton     Grass  Electric     2.7    58.9          0  12.0
82    83   Farfetchd     Water     Water     1.0    86.6          0  29.0
83    84       Doduo     Water    Normal     2.1    33.7          0  18.0
84    85      Dodrio     Water    Normal     3.7    21.2          0   3.0
85    86        Seel    Flying      Fire     2.7    77.4          0  12.0
86    87     Dewgong  Electric     Grass     2.4    67.0          0  15.0
87    88      Grimer   Psychic      Rock     3.9    25.8          0   1.0
88    89         Muk  Electric       NaN     0.8    33.1          0  31.0
89    90    Shellder      Rock  Electric     1.2    84.9          0  27.0
90    91    Cloyster    Dragon  Electric     1.2    80.6          0  27.0
91    92      Gastly    Normal  Electric     2.7    93.2          0  12.0
92    93     Haunter    Flying  Electric     3.7     2.2          0   3.0
93    94      Gengar      Fire    Normal     1.6    76.2          0  23.0
94    95        Onix   Psychic       NaN     3.0    59.6          0   9.0
95    96     Drowzee      Rock     Water     2.7    89.5          0  12.0
96    97       Hypno    Dragon     Grass     2.4    40.4          0  15.0
97    98      Krabby    Dragon   Psychic     0.8     8.8          0  31.0
98    99     Kingler    Poison    Dragon     2.1    59.8          0  18.0
99   100     Voltorb     Grass       NaN     2.2    27.1          0  17.0
100  101   Electrode   Psychic      Fire     2.0    29.9          0  19.0
101  102   Exeggcute     Water     Water     0.5    47.1          0  34.0
102  103   Exeggutor     Water    Flying     1.5    52.7          0  24.0
103  104      Cubone    Dragon    Flying     2.4    66.5          0  15.0
104  105     Marowak  Electric    Poison     3.5    85.0          0   5.0
105  106   Hitmonlee    Flying      Rock     2.5    91.6          0  14.0
106  107  Hitmonchan    Poison      Rock     1.1    36.6          0  28.0
107  108   Lickitung    Normal    Dragon     1.6    26.9          0  23.0
108  109     Koffing    Flying    Poison     0.4    34.9          0  35.0
109  110     Weezing      Rock      Fire     3.6    34.9          0   4.0
110  111     Rhyhorn      Rock    Normal     3.6    75.3          0   4.0
111  112      Rhydon     Grass     Grass     2.3    47.6          0  16.0
112  113     Chansey      Rock    Flying     2.6    17.5          0  13.0
113  114     Tangela      Fire    Poison     1.6    52.8          0  23.0
114  115  Kangaskhan     Grass    Flying     2.2    61.0          0  17.0
115  116      Horsea   Psychic    Flying     3.6    62.2          0   4.0
116  117      Seadra      Rock    Dragon     1.1    44.4          0  28.0
117  118     Goldeen     Grass    Dragon     1.9    17.5          0  20.0
118  119     Seaking    Poison     Water     3.6    17.9          0   4.0
119  120      Staryu    Flying      Rock     2.2    93.3          0  17.0
120  121     Starmie     Water     Water     0.4    47.9          0  35.0
121  122      MrMime      Rock      Fire     1.8    23.8          0  21.0
122  123     Scyther    Flying    Flying     2.6    28.2          0  13.0
123  124        Jynx      Fire      Rock     3.2    91.2          0   7.0
124  125  Electabuzz    Flying   Psychic     3.8    80.8          0   2.0
125  126      Magmar    Dragon      Fire     1.6    47.0          0  23.0
126  127      Pinsir     Water    Poison     1.8    82.4          0  21.0
127  128      Tauros    Flying    Normal     0.8    85.6          0  31.0
128  129    Magikarp     Water     Water     0.7    19.8          0  32.0
129  130    Gyarados     Grass     Water     3.8    47.5          0   2.0
130  131      Lapras    Poison     Grass     0.4    77.4          0  35.0
131  132       Ditto     Water     Grass     3.7    52.2          0   3.0
132  133       Eevee     Grass    Flying     2.2    98.9          0  17.0
133  134    Vaporeon   Psychic      Fire     2.3    39.6          0  16.0
134  135     Jolteon     Grass    Normal     2.4    16.5          0  15.0
135  136     Flareon     Water     Water     3.5    84.3          0   5.0
136  137     Porygon    Dragon  Electric     1.3    83.3          0  26.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0  30.0
138  139     Omastar  Electric      Rock     1.2    93.6          0  27.0
139  140      Kabuto     Water     Water     3.0    17.7          0   9.0
140  141    Kabutops      Rock     Grass     1.0    58.3          0  29.0
141  142  Aerodactyl    Poison    Poison     1.0    36.7          0  29.0
142  143     Snorlax     Grass    Normal     1.0    27.5          0  29.0
143  144    Articuno      Rock      Fire     3.9    25.2          1   1.0
144  145      Zapdos  Electric     Grass     2.7    36.7          1  12.0
145  146     Moltres    Dragon    Flying     3.3    54.6          1   6.0
146  147     Dratini      Rock    Flying     3.5    49.2          0   5.0
147  148   Dragonair    Poison     Grass     1.8    70.5          0  21.0
148  149   Dragonite    Flying   Psychic     1.3    40.1          0  26.0
149  150      Mewtwo     Water       NaN     2.9    70.6          1  10.0

In [74]:
# Percentage Ranking (pct=True) for statistic
df["Weight"].rank(pct = True)

38     0.006667
92     0.013333
43     0.020000
137    0.026667
4      0.033333
         ...
31     0.973333
30     0.980000
50     0.986667
25     0.993333
132    1.000000
Name: Weight, Length: 150, dtype: float64

In [75]:
# Percentage Ranking (pct=True)
df2["TypeRank"] = (df.groupby("Type1")["Weight"].rank(ascending=False))
print(df2.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary  Rank  TypeRank
0      1   Bulbasaur      Fire      Fire     2.1    91.1          0  18.0       2.0
1      2     Ivysaur     Water      Fire     1.2     6.6          0  27.0      20.0
2      3    Venusaur      Fire     Grass     1.4    17.6          0  25.0      11.0
3      4  Charmander    Flying    Dragon     1.4    29.0          0  25.0      17.0
4      5  Charmeleon    Normal    Poison     2.4     3.1          0  15.0      11.0
5      6   Charizard    Flying       NaN     2.7    33.9          0  12.0      15.0
6      7    Squirtle    Dragon      Rock     2.3    41.1          0  16.0      12.0
7      8   Wartortle      Fire   Psychic     2.7    38.5          0  12.0       9.0
8      9   Blastoise    Flying  Electric     1.1    49.3          0  28.0      11.0
9     10    Caterpie     Water  Electric     1.2    16.0          0  27.0      18.0
10    11     Metapod      Fire   Psychic     0.4    67.7          0  35.0       5.0
11    12  Butterfree      Fire       NaN     2.3    14.8          0  16.0      12.0
12    13      Weedle    Dragon       NaN     2.1    10.6          0  18.0      16.0
13    14      Kakuna    Flying      Rock     3.1    14.0          0   8.0      19.0
14    15    Beedrill  Electric    Poison     1.9    75.7          0  20.0       5.0
15    16      Pidgey    Dragon      Rock     1.4    94.8          0  25.0       1.0
16    17   Pidgeotto    Flying    Normal     1.7    33.4          0  22.0      16.0
17    18     Pidgeot     Grass       NaN     2.9    50.5          0  10.0       5.0
18    19     Rattata      Fire  Electric     2.0    88.7          0  19.0       3.0
19    20    Raticate    Dragon     Grass     0.8    31.4          0  31.0      14.0
20    21     Spearow      Rock    Normal     3.6    63.3          0   4.0       5.0
21    22      Fearow    Poison    Poison     2.1    92.3          0  18.0       1.0
22    23       Ekans      Rock    Poison     3.0    55.4          0   9.0       7.0
23    24       Arbok   Psychic      Fire     0.5    83.9          0  34.0       5.0
24    25     Pikachu    Poison    Poison     2.3    13.2          0  16.0      12.0
25    26      Raichu   Psychic    Poison     3.3    98.6          0   6.0       1.0
26    27   Sandshrew  Electric   Psychic     2.8    46.8          0  11.0       7.0
27    28   Sandslash    Dragon    Poison     3.3    67.0          0   6.0       7.0
28    29    NidoranF   Psychic      Rock     3.5    89.4          0   5.0       4.0
29    30    Nidorina   Psychic      Fire     0.5    93.5          0  34.0       3.0
30    31   Nidoqueen    Flying       NaN     3.3    97.2          0   6.0       1.0
31    32    NidoranM   Psychic    Dragon     2.5    96.5          0  14.0       2.0
32    33    Nidorino   Psychic    Dragon     0.6    19.7          0  33.0      12.0
33    34    Nidoking     Water     Water     0.6    68.3          0  33.0       6.0
34    35    Clefairy    Normal    Flying     0.5    48.1          0  34.0       5.0
35    36    Clefable     Water     Grass     2.6    51.0          0  13.0      10.0
36    37      Vulpix      Rock     Grass     0.9    68.0          0  30.0       4.0
37    38   Ninetales  Electric       NaN     1.0    45.4          0  29.0       8.0
38    39  Jigglypuff    Poison     Water     0.6     2.0          0  33.0      13.0
39    40  Wigglytuff     Grass      Fire     3.5     6.3          0   5.0      14.0
40    41       Zubat    Poison      Fire     1.4    78.5          0  25.0       2.0
41    42      Golbat   Psychic    Poison     2.3    19.4          0  16.0      13.0
42    43      Oddish     Water      Rock     3.7    13.4          0   3.0      19.0
43    44       Gloom      Fire    Flying     3.7     2.3          0   3.0      13.0
44    45   Vileplume    Flying    Normal     1.5    43.1          0  24.0      12.0
45    46       Paras    Normal      Rock     1.9    70.6          0  20.0       3.0
46    47    Parasect    Flying      Rock     1.3    90.0          0  26.0       5.0
47    48     Venonat  Electric  Electric     2.0    81.7          0  19.0       4.0
48    49    Venomoth    Normal    Normal     2.8    78.6          0  11.0       2.0
49    50     Diglett    Normal     Water     2.4     4.5          0  15.0      10.0
50    51     Dugtrio  Electric      Rock     0.7    98.2          0  32.0       1.0
51    52      Meowth   Psychic     Grass     3.7    41.4          0   3.0       8.0
52    53     Persian      Fire  Electric     0.6    49.5          0  33.0       8.0
53    54     Psyduck     Grass       NaN     2.6     9.1          0  13.0      12.0
54    55     Golduck    Dragon  Electric     1.0    14.8          0  29.0      15.0
55    56      Mankey      Rock       NaN     0.3    29.0          0  36.0      11.0
56    57    Primeape   Psychic    Poison     1.9     3.5          0  20.0      15.0
57    58   Growlithe    Normal     Water     3.8    49.3          0   2.0       4.0
58    59    Arcanine    Flying    Normal     0.9    92.8          0  30.0       3.0
59    60     Poliwag     Water    Dragon     1.8    39.7          0  21.0      13.0
60    61   Poliwhirl    Normal      Rock     1.5    43.2          0  24.0       6.0
61    62   Poliwrath    Poison      Fire     2.4    69.2          0  15.0       5.0
62    63        Abra      Fire      Rock     0.5    28.5          0  34.0      10.0
63    64     Kadabra    Dragon    Flying     3.2    69.3          0   7.0       6.0
64    65    Alakazam    Flying    Normal     0.8    11.5          0  31.0      20.0
65    66      Machop    Dragon     Water     3.0    56.1          0   9.0       9.0
66    67     Machoke    Poison      Rock     3.9    55.7          0   1.0       7.0
67    68     Machamp    Flying    Poison     0.8    66.8          0  31.0      10.0
68    69  Bellsprout   Psychic  Electric     1.6    16.3          0  23.0      14.0
69    70  Weepinbell  Electric    Poison     1.4    10.2          0  25.0      11.0
70    71  Victreebel    Poison       NaN     2.6    37.0          0  13.0       8.0
71    72   Tentacool     Grass   Psychic     0.8     8.0          0  31.0      13.0
72    73  Tentacruel      Fire    Poison     3.9    53.6          0   1.0       6.0
73    74     Geodude    Dragon    Flying     0.6    84.2          0  33.0       2.0
74    75    Graveler    Normal    Dragon     1.4    17.3          0  25.0       9.0
75    76       Golem    Flying     Grass     3.1    68.2          0   8.0       9.0
76    77      Ponyta    Dragon   Psychic     1.4    74.6          0  25.0       5.0
77    78    Rapidash     Water   Psychic     2.6    69.5          0  13.0       5.0
78    79    Slowpoke    Normal      Fire     3.0    41.9          0   9.0       7.0
79    80     Slowbro     Water   Psychic     2.2    55.3          0  17.0       7.0
80    81   Magnemite     Grass    Flying     1.2    53.1          0  27.0       4.0
81    82    Magneton     Grass  Electric     2.7    58.9          0  12.0       3.0
82    83   Farfetchd     Water     Water     1.0    86.6          0  29.0       1.0
83    84       Doduo     Water    Normal     2.1    33.7          0  18.0      14.0
84    85      Dodrio     Water    Normal     3.7    21.2          0   3.0      15.0
85    86        Seel    Flying      Fire     2.7    77.4          0  12.0       8.0
86    87     Dewgong  Electric     Grass     2.4    67.0          0  15.0       6.0
87    88      Grimer   Psychic      Rock     3.9    25.8          0   1.0      11.0
88    89         Muk  Electric       NaN     0.8    33.1          0  31.0      10.0
89    90    Shellder      Rock  Electric     1.2    84.9          0  27.0       2.0
90    91    Cloyster    Dragon  Electric     1.2    80.6          0  27.0       4.0
91    92      Gastly    Normal  Electric     2.7    93.2          0  12.0       1.0
92    93     Haunter    Flying  Electric     3.7     2.2          0   3.0      21.0
93    94      Gengar      Fire    Normal     1.6    76.2          0  23.0       4.0
94    95        Onix   Psychic       NaN     3.0    59.6          0   9.0       7.0
95    96     Drowzee      Rock     Water     2.7    89.5          0  12.0       1.0
96    97       Hypno    Dragon     Grass     2.4    40.4          0  15.0      13.0
97    98      Krabby    Dragon   Psychic     0.8     8.8          0  31.0      17.0
98    99     Kingler    Poison    Dragon     2.1    59.8          0  18.0       6.0
99   100     Voltorb     Grass       NaN     2.2    27.1          0  17.0       9.0
100  101   Electrode   Psychic      Fire     2.0    29.9          0  19.0      10.0
101  102   Exeggcute     Water     Water     0.5    47.1          0  34.0      12.0
102  103   Exeggutor     Water    Flying     1.5    52.7          0  24.0       8.0
103  104      Cubone    Dragon    Flying     2.4    66.5          0  15.0       8.0
104  105     Marowak  Electric    Poison     3.5    85.0          0   5.0       3.0
105  106   Hitmonlee    Flying      Rock     2.5    91.6          0  14.0       4.0
106  107  Hitmonchan    Poison      Rock     1.1    36.6          0  28.0      10.0
107  108   Lickitung    Normal    Dragon     1.6    26.9          0  23.0       8.0
108  109     Koffing    Flying    Poison     0.4    34.9          0  35.0      14.0
109  110     Weezing      Rock      Fire     3.6    34.9          0   4.0      10.0
110  111     Rhyhorn      Rock    Normal     3.6    75.3          0   4.0       3.0
111  112      Rhydon     Grass     Grass     2.3    47.6          0  16.0       6.0
112  113     Chansey      Rock    Flying     2.6    17.5          0  13.0      14.0
113  114     Tangela      Fire    Poison     1.6    52.8          0  23.0       7.0
114  115  Kangaskhan     Grass    Flying     2.2    61.0          0  17.0       2.0
115  116      Horsea   Psychic    Flying     3.6    62.2          0   4.0       6.0
116  117      Seadra      Rock    Dragon     1.1    44.4          0  28.0       9.0
117  118     Goldeen     Grass    Dragon     1.9    17.5          0  20.0      10.0
118  119     Seaking    Poison     Water     3.6    17.9          0   4.0      11.0
119  120      Staryu    Flying      Rock     2.2    93.3          0  17.0       2.0
120  121     Starmie     Water     Water     0.4    47.9          0  35.0      11.0
121  122      MrMime      Rock      Fire     1.8    23.8          0  21.0      13.0
122  123     Scyther    Flying    Flying     2.6    28.2          0  13.0      18.0
123  124        Jynx      Fire      Rock     3.2    91.2          0   7.0       1.0
124  125  Electabuzz    Flying   Psychic     3.8    80.8          0   2.0       7.0
125  126      Magmar    Dragon      Fire     1.6    47.0          0  23.0      11.0
126  127      Pinsir     Water    Poison     1.8    82.4          0  21.0       3.0
127  128      Tauros    Flying    Normal     0.8    85.6          0  31.0       6.0
128  129    Magikarp     Water     Water     0.7    19.8          0  32.0      16.0
129  130    Gyarados     Grass     Water     3.8    47.5          0   2.0       7.0
130  131      Lapras    Poison     Grass     0.4    77.4          0  35.0       3.0
131  132       Ditto     Water     Grass     3.7    52.2          0   3.0       9.0
132  133       Eevee     Grass    Flying     2.2    98.9          0  17.0       1.0
133  134    Vaporeon   Psychic      Fire     2.3    39.6          0  16.0       9.0
134  135     Jolteon     Grass    Normal     2.4    16.5          0  15.0      11.0
135  136     Flareon     Water     Water     3.5    84.3          0   5.0       2.0
136  137     Porygon    Dragon  Electric     1.3    83.3          0  26.0       3.0
137  138     Omanyte  Electric   Psychic     0.9     2.7          0  30.0      12.0
138  139     Omastar  Electric      Rock     1.2    93.6          0  27.0       2.0
139  140      Kabuto     Water     Water     3.0    17.7          0   9.0      17.0
140  141    Kabutops      Rock     Grass     1.0    58.3          0  29.0       6.0
141  142  Aerodactyl    Poison    Poison     1.0    36.7          0  29.0       9.0
142  143     Snorlax     Grass    Normal     1.0    27.5          0  29.0       8.0
143  144    Articuno      Rock      Fire     3.9    25.2          1   1.0      12.0
144  145      Zapdos  Electric     Grass     2.7    36.7          1  12.0       9.0
145  146     Moltres    Dragon    Flying     3.3    54.6          1   6.0      10.0
146  147     Dratini      Rock    Flying     3.5    49.2          0   5.0       8.0
147  148   Dragonair    Poison     Grass     1.8    70.5          0  21.0       4.0
148  149   Dragonite    Flying   Psychic     1.3    40.1          0  26.0      13.0
149  150      Mewtwo     Water       NaN     2.9    70.6          1  10.0       4.0

In [76]:
# Top N Rows After Ranking
df2.sort_values(by = "Weight").head(3)

,No,Name,Type1,Type2,Height,Weight,Legendary,Rank,TypeRank
38,39,Jigglypuff,Poison,Water,0.6,2.0,0,33.0,13.0
92,93,Haunter,Flying,Electric,3.7,2.2,0,3.0,21.0
43,44,Gloom,Fire,Flying,3.7,2.3,0,3.0,13.0

In [77]:
#or
df2.nlargest(3 , "Weight")

      No     Name     Type1   Type2  Height  Weight  Legendary  Rank  TypeRank
132  133    Eevee     Grass  Flying     2.2    98.9          0  17.0       1.0
25    26   Raichu   Psychic  Poison     3.3    98.6          0   6.0       1.0
50    51  Dugtrio  Electric    Rock     0.7    98.2          0  32.0       1.0