In [47]:
import pandas as pd

In [48]:
left_df = pd.DataFrame({"Id" : [101,102,103] , "Name" : ["Het" , "Meet" , "Preet"]})

In [49]:
right_df = pd.DataFrame({"Id" : [101,102,103] ,  "Mark" : [90 , 80 , 70]})

In [50]:
# PART 1 : merge() is like SQL JOIN.
pd.merge(left_df , right_df , on="Id")

    Id   Name  Mark
0  101    Het    90
1  102   Meet    80
2  103  Preet    70

In [51]:
# There are 4 main joins.
# Exactly same as SQL joins.

In [52]:
# 1. INNER JOIN (Default)
# Keeps only matching rows.
student = pd.DataFrame({"Id" : [101,102,103] , "Name" : ["Het" , "Meet" , "Preet"]})
mark = pd.DataFrame({"Id" : [101,102,104] ,  "Mark" : [90 , 80 , 70]})
pd.merge(student , mark , on="Id" , how="inner")

    Id  Name  Mark
0  101   Het    90
1  102  Meet    80

In [53]:
# 2. LEFT JOIN
# Keeps ALL rows from LEFT dataframe.
pd.merge(student , mark , on="Id" , how="left")

    Id   Name  Mark
0  101    Het  90.0
1  102   Meet  80.0
2  103  Preet   NaN

In [54]:
# 3. RIGHT JOIN
# Keeps ALL rows from RIGHT dataframe.
pd.merge(student , mark , on="Id" , how="right")

    Id  Name  Mark
0  101   Het    90
1  102  Meet    80
2  104   NaN    70

In [55]:
# 4. OUTER JOIN
# Keeps ALL rows from BOTH tables.
pd.merge(student , mark , on="Id" , how="outer")

    Id   Name  Mark
0  101    Het  90.0
1  102   Meet  80.0
2  103  Preet   NaN
3  104    NaN  70.0

In [56]:
# PART 2 — Different Column Names
# Sometimes common columns have different names.
student2 = pd.DataFrame({"Id" : [101,102,103] , "Name" : ["Het" , "Meet" , "Preet"]})
mark2 = pd.DataFrame({"StudentId" : [101,102,104] ,  "Mark" : [90 , 80 , 70]})
pd.merge(student2,mark2,left_on="Id",right_on="StudentId")

    Id  Name  StudentId  Mark
0  101   Het        101    90
1  102  Meet        102    80

In [57]:
# PART 3 — Multiple Key Columns
# You can merge using multiple columns.
student3 = pd.DataFrame({"Id" : [101,102,103] , "Name" : ["Het" , "Meet" , "Preet"] , "City" : ["Rajkot" , "Baroda" , "Ahmedabad"]})
mark3 = pd.DataFrame({"Id" : [101,102,103] ,  "Mark" : [90 , 80 , 70] , "City" : ["Rajkot" , "Baroda" , " Surat"]})
pd.merge(student3,mark3,on=["Id","City"])

    Id  Name    City  Mark
0  101   Het  Rajkot    90
1  102  Meet  Baroda    80

In [58]:
# PART 4 — Duplicate Column Names
# Suppose both tables contain "Name" column.
student4 = pd.DataFrame({"Id" : [101,102,103] , "Name" : ["Het" , "Meet" , "Preet"]})
mark4 = pd.DataFrame({"Id" : [101,102,104] ,  "Name" : ["Het" , "Meet" , "Rohan"] , "Mark" : [90,80,70]})
pd.merge(student4,mark4,on="Id")
pd.merge(student4,mark4,on="Id",suffixes=["-Student" , "-Mark"])

    Id Name-Student Name-Mark  Mark
0  101          Het       Het    90
1  102         Meet      Meet    80

In [59]:
# PART 5 — indicator=True
# Very important for debugging merges
pd.merge(student,mark,on="Id",how="outer",indicator=True)

    Id   Name  Mark      _merge
0  101    Het  90.0        both
1  102   Meet  80.0        both
2  103  Preet   NaN   left_only
3  104    NaN  70.0  right_only

In [60]:
# PART 6 — Merge on Index
# Normally merge uses columns.
# Can also merge using index.
pd.merge(student,mark,left_index=True,right_index=True)

   Id_x   Name  Id_y  Mark
0   101    Het   101    90
1   102   Meet   102    80
2   103  Preet   104    70

In [65]:
# PART 7 — join() Function
# Simpler version of merge.
# Mostly used with indexes.
student2.join(mark2)

    Id   Name  StudentId  Mark
0  101    Het        101    90
1  102   Meet        102    80
2  103  Preet        104    70

In [66]:
pd.merge(student2,mark2,left_on="Id",right_on="StudentId")

    Id  Name  StudentId  Mark
0  101   Het        101    90
1  102  Meet        102    80

In [67]:
# PART 8 — concat() ⭐
# Very important.
# Used to STACK dataframes.
# Two types:
# Vertical stacking
# Horizontal stacking

In [68]:
# Vertical Concatenation
pd.concat([student,mark])

    Id   Name  Mark
0  101    Het   NaN
1  102   Meet   NaN
2  103  Preet   NaN
0  101    NaN  90.0
1  102    NaN  80.0
2  104    NaN  70.0

In [69]:
# Horizontal Concatenation
pd.concat([student,mark] , axis=1)

    Id   Name   Id  Mark
0  101    Het  101    90
1  102   Meet  102    80
2  103  Preet  104    70

In [70]:
pd.concat([student,mark] , ignore_index=True)

    Id   Name  Mark
0  101    Het   NaN
1  102   Meet   NaN
2  103  Preet   NaN
3  101    NaN  90.0
4  102    NaN  80.0
5  104    NaN  70.0